# Form implementation generated from reading ui file 'Ui/medical_history_addEdit_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MedicalHistoryDialog(object):
    def setupUi(self, MedicalHistoryDialog):
        MedicalHistoryDialog.setObjectName("MedicalHistoryDialog")
        MedicalHistoryDialog.resize(600, 650)
        MedicalHistoryDialog.setStyleSheet("background-color: rgb(240, 230, 240);")
        self.verticalLayout = QtWidgets.QVBoxLayout(MedicalHistoryDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(parent=MedicalHistoryDialog)
        self.title_label.setStyleSheet("font-family: \'Arial Black\'; font-size: 20px; color: rgb(26, 26, 62); padding: 10px;")
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.form_frame = QtWidgets.QFrame(parent=MedicalHistoryDialog)
        self.form_frame.setStyleSheet("background-color: rgb(236, 198, 220); border-radius: 15px; border: 1px solid rgb(158, 136, 163);")
        self.form_frame.setObjectName("form_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.form_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.notes_label = QtWidgets.QLabel(parent=self.form_frame)
        self.notes_label.setStyleSheet("font-weight: bold; color: rgb(26, 26, 62);")
        self.notes_label.setObjectName("notes_label")
        self.gridLayout.addWidget(self.notes_label, 3, 0, 1, 1)
        self.condition_label = QtWidgets.QLabel(parent=self.form_frame)
        self.condition_label.setStyleSheet("font-weight: bold; color: rgb(26, 26, 62);\n"
"border: none;")
        self.condition_label.setObjectName("condition_label")
        self.gridLayout.addWidget(self.condition_label, 0, 0, 1, 1)
        self.diagnosed_label = QtWidgets.QLabel(parent=self.form_frame)
        self.diagnosed_label.setStyleSheet("font-weight: bold; color: rgb(26, 26, 62);\n"
"border: none;")
        self.diagnosed_label.setObjectName("diagnosed_label")
        self.gridLayout.addWidget(self.diagnosed_label, 1, 0, 1, 1)
        self.status_label = QtWidgets.QLabel(parent=self.form_frame)
        self.status_label.setStyleSheet("font-weight: bold; color: rgb(26, 26, 62);\n"
"border: none;")
        self.status_label.setObjectName("status_label")
        self.gridLayout.addWidget(self.status_label, 2, 0, 1, 1)
        self.condition_combo = QtWidgets.QComboBox(parent=self.form_frame)
        self.condition_combo.setStyleSheet("background-color: white; border-radius: 8px; padding: 5px; border: 1px solid rgb(158, 136, 163);")
        self.condition_combo.setEditable(True)
        self.condition_combo.setObjectName("condition_combo")
        self.condition_combo.addItem("")
        self.condition_combo.addItem("")
        self.condition_combo.addItem("")
        self.condition_combo.addItem("")
        self.condition_combo.addItem("")
        self.condition_combo.addItem("")
        self.gridLayout.addWidget(self.condition_combo, 0, 1, 1, 1)
        self.notes_text = QtWidgets.QTextEdit(parent=self.form_frame)
        self.notes_text.setStyleSheet("background-color: white; border-radius: 8px; padding: 5px; border: 1px solid rgb(158, 136, 163);")
        self.notes_text.setObjectName("notes_text")
        self.gridLayout.addWidget(self.notes_text, 3, 1, 1, 1)
        self.diagnosed_date = QtWidgets.QDateEdit(parent=self.form_frame)
        self.diagnosed_date.setStyleSheet("background-color: white; border-radius: 8px; padding: 5px; border: 1px solid rgb(158, 136, 163);")
        self.diagnosed_date.setCalendarPopup(True)
        self.diagnosed_date.setDate(QtCore.QDate(2024, 3, 10))
        self.diagnosed_date.setObjectName("diagnosed_date")
        self.gridLayout.addWidget(self.diagnosed_date, 1, 1, 1, 1)
        self.status_combo = QtWidgets.QComboBox(parent=self.form_frame)
        self.status_combo.setStyleSheet("background-color: white; border-radius: 8px; padding: 5px; border: 1px solid rgb(158, 136, 163);")
        self.status_combo.setObjectName("status_combo")
        self.status_combo.addItem("")
        self.status_combo.addItem("")
        self.status_combo.addItem("")
        self.status_combo.addItem("")
        self.gridLayout.addWidget(self.status_combo, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.form_frame)
        self.button_frame = QtWidgets.QFrame(parent=MedicalHistoryDialog)
        self.button_frame.setStyleSheet("background-color: transparent;")
        self.button_frame.setObjectName("button_frame")
        self.button_layout = QtWidgets.QHBoxLayout(self.button_frame)
        self.button_layout.setObjectName("button_layout")
        self.save_btn = QtWidgets.QPushButton(parent=self.button_frame)
        self.save_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(192, 116, 182);\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 90, 160);\n"
"}")
        self.save_btn.setObjectName("save_btn")
        self.button_layout.addWidget(self.save_btn)
        self.cancel_btn = QtWidgets.QPushButton(parent=self.button_frame)
        self.cancel_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(100, 100, 100);\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 10px 20px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80, 80, 80);\n"
"}")
        self.cancel_btn.setObjectName("cancel_btn")
        self.button_layout.addWidget(self.cancel_btn)
        self.verticalLayout.addWidget(self.button_frame)

        self.retranslateUi(MedicalHistoryDialog)
        QtCore.QMetaObject.connectSlotsByName(MedicalHistoryDialog)

    def retranslateUi(self, MedicalHistoryDialog):
        _translate = QtCore.QCoreApplication.translate
        MedicalHistoryDialog.setWindowTitle(_translate("MedicalHistoryDialog", "Add/Edit Medical Condition"))
        self.title_label.setText(_translate("MedicalHistoryDialog", "Medical Condition Details"))
        self.notes_label.setText(_translate("MedicalHistoryDialog", "Clinical Notes:"))
        self.condition_label.setText(_translate("MedicalHistoryDialog", "Medical Condition:*"))
        self.diagnosed_label.setText(_translate("MedicalHistoryDialog", "Diagnosed Date:*"))
        self.status_label.setText(_translate("MedicalHistoryDialog", "Status:*"))
        self.condition_combo.setItemText(0, _translate("MedicalHistoryDialog", "Gestational Diabetes"))
        self.condition_combo.setItemText(1, _translate("MedicalHistoryDialog", "Anemia"))
        self.condition_combo.setItemText(2, _translate("MedicalHistoryDialog", "UTI"))
        self.condition_combo.setItemText(3, _translate("MedicalHistoryDialog", "Hypothyroidism"))
        self.condition_combo.setItemText(4, _translate("MedicalHistoryDialog", "Hypertension"))
        self.condition_combo.setItemText(5, _translate("MedicalHistoryDialog", "Preeclampsia"))
        self.status_combo.setItemText(0, _translate("MedicalHistoryDialog", "Ongoing"))
        self.status_combo.setItemText(1, _translate("MedicalHistoryDialog", "Resolved"))
        self.status_combo.setItemText(2, _translate("MedicalHistoryDialog", "In Remission"))
        self.status_combo.setItemText(3, _translate("MedicalHistoryDialog", "Chronic"))
        self.save_btn.setText(_translate("MedicalHistoryDialog", "Save"))
        self.cancel_btn.setText(_translate("MedicalHistoryDialog", "Cancel"))
