# Form implementation generated from reading ui file 'new_appointment_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(455, 350)
        Dialog.setMinimumSize(QtCore.QSize(400, 350))
        Dialog.setStyleSheet("background-color: #ECC6DC;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setStyleSheet("background-color: white;\n"
"\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_3.setStyleSheet("background-color: #854E6B;\n"
"color: white;\n"
"border: none;\n"
"padding: 8px 20px;\n"
"border-radius: 15px;\n"
"font-weight: bold;\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget)
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.comboBox = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox.setStyleSheet("background-color: #854E6B;\n"
"color: white;\n"
"\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.comboBox_2 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_2.setStyleSheet("background-color: #854E6B;\n"
"color: white;\n"
"\n"
"")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.comboBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.widget_2 = QtWidgets.QWidget(parent=Dialog)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton.setStyleSheet("background-color: #9C27B0;\n"
"color: white;\n"
"border: none;\n"
"padding: 8px 20px;\n"
"border-radius: 15px;\n"
"font-weight: bold;")
        self.pushButton.setDefault(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_2.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: none;\n"
"padding: 8px 20px;\n"
"border-radius: 15px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit, self.comboBox)
        Dialog.setTabOrder(self.comboBox, self.comboBox_2)
        Dialog.setTabOrder(self.comboBox_2, self.pushButton)
        Dialog.setTabOrder(self.pushButton, self.pushButton_2)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "New Appointment"))
        self.label.setText(_translate("Dialog", "New Appointment"))
        self.label_2.setText(_translate("Dialog", "Patient"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Enter patient\'s full name"))
        self.label_3.setText(_translate("Dialog", "Date"))
        self.pushButton_3.setText(_translate("Dialog", "Select Date"))
        self.label_4.setText(_translate("Dialog", "Type of Visit"))
        self.comboBox.setItemText(0, _translate("Dialog", "Prenatal Care"))
        self.comboBox.setItemText(1, _translate("Dialog", "General Check-up"))
        self.comboBox.setItemText(2, _translate("Dialog", "Consultation"))
        self.comboBox.setItemText(3, _translate("Dialog", "Emergency Visit"))
        self.comboBox.setItemText(4, _translate("Dialog", "Family Planning"))
        self.comboBox.setItemText(5, _translate("Dialog", "Screening & Tests"))
        self.comboBox.setItemText(6, _translate("Dialog", "Vaccination"))
        self.label_5.setText(_translate("Dialog", "Time"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "9:00 AM"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "9: 30 AM"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "10:00 AM"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "10:30 AM"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "11:00 AM"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "1:00 PM"))
        self.comboBox_2.setItemText(6, _translate("Dialog", "2:00 PM"))
        self.comboBox_2.setItemText(7, _translate("Dialog", "3:00 PM"))
        self.comboBox_2.setItemText(8, _translate("Dialog", "4:00 PM"))
        self.pushButton.setText(_translate("Dialog", "Save"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))
