# Form implementation generated from reading ui file 'Ui/past_pregnancy_add_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(391, 390)
        self.frame_2 = QtWidgets.QFrame(parent=Dialog)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 401, 391))
        self.frame_2.setStyleSheet("background-color: rgb(240, 230, 240);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.address_label = QtWidgets.QLabel(parent=self.frame_2)
        self.address_label.setGeometry(QtCore.QRect(60, 10, 271, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.address_label.sizePolicy().hasHeightForWidth())
        self.address_label.setSizePolicy(sizePolicy)
        self.address_label.setStyleSheet("font: 16pt \"Segoe UI\";")
        self.address_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.address_label.setObjectName("address_label")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 340, 191, 28))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.episiotomy_label = QtWidgets.QLabel(parent=self.frame_2)
        self.episiotomy_label.setGeometry(QtCore.QRect(199, 129, 91, 16))
        self.episiotomy_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.episiotomy_label.setObjectName("episiotomy_label")
        self.complication_placeholder = QtWidgets.QLineEdit(parent=self.frame_2)
        self.complication_placeholder.setGeometry(QtCore.QRect(39, 209, 151, 31))
        self.complication_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.complication_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.complication_placeholder.setObjectName("complication_placeholder")
        self.delivery_date_placeholder = QtWidgets.QLineEdit(parent=self.frame_2)
        self.delivery_date_placeholder.setGeometry(QtCore.QRect(199, 89, 151, 31))
        self.delivery_date_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.delivery_date_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.delivery_date_placeholder.setObjectName("delivery_date_placeholder")
        self.delivery_date_label = QtWidgets.QLabel(parent=self.frame_2)
        self.delivery_date_label.setGeometry(QtCore.QRect(39, 69, 91, 16))
        self.delivery_date_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.delivery_date_label.setObjectName("delivery_date_label")
        self.presentation_label = QtWidgets.QLabel(parent=self.frame_2)
        self.presentation_label.setGeometry(QtCore.QRect(39, 129, 141, 16))
        self.presentation_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.presentation_label.setObjectName("presentation_label")
        self.complication_label = QtWidgets.QLabel(parent=self.frame_2)
        self.complication_label.setGeometry(QtCore.QRect(39, 189, 91, 16))
        self.complication_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.complication_label.setObjectName("complication_label")
        self.presentation_placeholder = QtWidgets.QLineEdit(parent=self.frame_2)
        self.presentation_placeholder.setGeometry(QtCore.QRect(39, 149, 151, 31))
        self.presentation_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.presentation_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.presentation_placeholder.setObjectName("presentation_placeholder")
        self.delivery_type_label = QtWidgets.QLabel(parent=self.frame_2)
        self.delivery_type_label.setGeometry(QtCore.QRect(199, 69, 101, 16))
        self.delivery_type_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.delivery_type_label.setObjectName("delivery_type_label")
        self.baby_weight_placeholder = QtWidgets.QLineEdit(parent=self.frame_2)
        self.baby_weight_placeholder.setGeometry(QtCore.QRect(199, 209, 151, 31))
        self.baby_weight_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.baby_weight_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.baby_weight_placeholder.setObjectName("baby_weight_placeholder")
        self.baby_weight_label = QtWidgets.QLabel(parent=self.frame_2)
        self.baby_weight_label.setGeometry(QtCore.QRect(199, 189, 91, 16))
        self.baby_weight_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.baby_weight_label.setObjectName("baby_weight_label")
        self.outcome_label = QtWidgets.QLabel(parent=self.frame_2)
        self.outcome_label.setGeometry(QtCore.QRect(39, 249, 91, 16))
        self.outcome_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.outcome_label.setObjectName("outcome_label")
        self.delivery_dat_placeholder = QtWidgets.QDateEdit(parent=self.frame_2)
        self.delivery_dat_placeholder.setGeometry(QtCore.QRect(39, 89, 151, 31))
        self.delivery_dat_placeholder.setStyleSheet("QDateEdit {\n"
"    border: 1px solid #6c6c8a;\n"
"    border-radius: 10px;\n"
"    padding: 6px 10px;\n"
"    padding-right: 30px; /* space for icon */\n"
"    background: transparent;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    border: none;\n"
"    width: 20px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow {\n"
"    image: url(:/icons/calendar.png); /* optional custom icon */\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}")
        self.delivery_dat_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.delivery_dat_placeholder.setCalendarPopup(True)
        self.delivery_dat_placeholder.setObjectName("delivery_dat_placeholder")
        self.comboBox = QtWidgets.QComboBox(parent=self.frame_2)
        self.comboBox.setGeometry(QtCore.QRect(39, 269, 151, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.cancel_btn_2 = QtWidgets.QPushButton(parent=self.frame_2)
        self.cancel_btn_2.setGeometry(QtCore.QRect(100, 340, 92, 26))
        self.cancel_btn_2.setStyleSheet("border-radius: 12px;\n"
"padding: 4px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.cancel_btn_2.setObjectName("cancel_btn_2")
        self.save_btn_2 = QtWidgets.QPushButton(parent=self.frame_2)
        self.save_btn_2.setGeometry(QtCore.QRect(198, 340, 91, 26))
        self.save_btn_2.setStyleSheet("border-radius: 12px;\n"
"padding: 4px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.save_btn_2.setObjectName("save_btn_2")
        self.Episiotomy_placeholder = QtWidgets.QComboBox(parent=self.frame_2)
        self.Episiotomy_placeholder.setGeometry(QtCore.QRect(200, 150, 151, 31))
        self.Episiotomy_placeholder.setObjectName("Episiotomy_placeholder")
        self.Episiotomy_placeholder.addItem("")
        self.Episiotomy_placeholder.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.address_label.setText(_translate("Dialog", "Add Past Pregnancy"))
        self.episiotomy_label.setText(_translate("Dialog", "Episiotomy"))
        self.complication_placeholder.setText(_translate("Dialog", "e.g., Perineal tear, None"))
        self.delivery_date_placeholder.setText(_translate("Dialog", "e.g., Occiput posterior"))
        self.delivery_date_label.setText(_translate("Dialog", "Delivery Date"))
        self.presentation_label.setText(_translate("Dialog", "Presentation"))
        self.complication_label.setText(_translate("Dialog", "Complication"))
        self.presentation_placeholder.setText(_translate("Dialog", "e.g., Cephalic"))
        self.delivery_type_label.setText(_translate("Dialog", "Delivery Type"))
        self.baby_weight_placeholder.setText(_translate("Dialog", "e.g., Husband"))
        self.baby_weight_label.setText(_translate("Dialog", "Baby Weight"))
        self.outcome_label.setText(_translate("Dialog", "Outcome"))
        self.comboBox.setItemText(0, _translate("Dialog", "Full Term"))
        self.comboBox.setItemText(1, _translate("Dialog", "Preterm"))
        self.comboBox.setItemText(2, _translate("Dialog", "Miscarriage"))
        self.comboBox.setItemText(3, _translate("Dialog", "Abortion"))
        self.cancel_btn_2.setText(_translate("Dialog", "Cancel"))
        self.save_btn_2.setText(_translate("Dialog", "Save"))
        self.Episiotomy_placeholder.setItemText(0, _translate("Dialog", "Yes"))
        self.Episiotomy_placeholder.setItemText(1, _translate("Dialog", "No"))
