# Form implementation generated from reading ui file 'Ui/dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DashboardScreen(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1224, 674)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 60, 231, 581))
        self.frame.setStyleSheet(" background-color: rgb(192, 116, 182)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 180, 221, 41))
        self.pushButton.setStyleSheet("background-color: rgb(240, 230, 240)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 230, 191, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(240, 230, 240)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 280, 191, 41))
        self.pushButton_3.setStyleSheet("background-color: rgb(240, 230, 240)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 330, 191, 41))
        self.pushButton_4.setStyleSheet("background-color: rgb(240, 230, 240)")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 500, 191, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1231, 61))
        self.frame_2.setStyleSheet("background-color: rgb(26, 26, 62)\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(110, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.logo = QtWidgets.QLabel(parent=self.frame_2)
        self.logo.setGeometry(QtCore.QRect(40, 10, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(50, 50))
        self.logo.setObjectName("logo")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(230, 60, 1001, 601))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("background-color: rgb(240, 230, 240)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setGeometry(QtCore.QRect(40, 20, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.patient_table = QtWidgets.QTableWidget(parent=self.frame_3)
        self.patient_table.setGeometry(QtCore.QRect(50, 260, 621, 191))
        self.patient_table.setMinimumSize(QtCore.QSize(621, 191))
        self.patient_table.setMaximumSize(QtCore.QSize(700, 200))
        self.patient_table.setAutoFillBackground(True)
        self.patient_table.setStyleSheet("QTableWidget {\n"
"    background-color:rgb(236, 198, 220);\n"
"    border: 1px solid rgb(158, 136, 163);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    background-color: rgb(236, 198, 220);\n"
"    color: rgb(21, 23, 61);\n"
"    padding: 8px;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(210, 177, 200);\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: rgb(240, 210, 230);\n"
"    color: rgb(21, 23, 61);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(236, 198, 220);\n"
"    color: rgb(21, 23, 61);\n"
"    font-weight: bold;\n"
"    font-size: 10px;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(155, 132, 160);\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: white;\n"
"    width: 6px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(178, 100, 168);\n"
"    border-radius: 3px;\n"
"}")
        self.patient_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.patient_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.patient_table.setAlternatingRowColors(False)
        self.patient_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.patient_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.patient_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.patient_table.setShowGrid(False)
        self.patient_table.setObjectName("patient_table")
        self.patient_table.setColumnCount(3)
        self.patient_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setHorizontalHeaderItem(2, item)
        self.patient_table.horizontalHeader().setCascadingSectionResizes(False)
        self.patient_table.horizontalHeader().setDefaultSectionSize(170)
        self.patient_table.horizontalHeader().setHighlightSections(True)
        self.patient_table.horizontalHeader().setMinimumSectionSize(32)
        self.patient_table.horizontalHeader().setSortIndicatorShown(True)
        self.patient_table.horizontalHeader().setStretchLastSection(True)
        self.patient_table.verticalHeader().setVisible(False)
        self.patient_table.verticalHeader().setCascadingSectionResizes(False)
        self.today_appointment = QtWidgets.QTableView(parent=self.frame_3)
        self.today_appointment.setGeometry(QtCore.QRect(680, 260, 291, 191))
        self.today_appointment.setMaximumSize(QtCore.QSize(300, 200))
        self.today_appointment.setStyleSheet("background-color: rgb(235, 197, 219);\n"
"border-radius: 15px;\n"
"border: 1px solid rgb(158, 136, 163)")
        self.today_appointment.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.today_appointment.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.today_appointment.setObjectName("today_appointment")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(50, 230, 131, 21))
        self.label_3.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: rgb(21, 23, 61);\n"
"    border: none;\n"
"    background: transparent;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.Todays_appointment_TA = QtWidgets.QLabel(parent=self.frame_3)
        self.Todays_appointment_TA.setGeometry(QtCore.QRect(680, 230, 241, 21))
        self.Todays_appointment_TA.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: rgb(21, 23, 61);\n"
"    border: none;\n"
"    background: transparent;\n"
"}")
        self.Todays_appointment_TA.setObjectName("Todays_appointment_TA")
        self.content_container_TA = QtWidgets.QFrame(parent=self.frame_3)
        self.content_container_TA.setGeometry(QtCore.QRect(695, 280, 260, 78))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.content_container_TA.sizePolicy().hasHeightForWidth())
        self.content_container_TA.setSizePolicy(sizePolicy)
        self.content_container_TA.setMinimumSize(QtCore.QSize(260, 78))
        self.content_container_TA.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid rgb(162, 139, 166);\n"
"background-color: rgb(236, 198, 220);")
        self.content_container_TA.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.content_container_TA.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.content_container_TA.setObjectName("content_container_TA")
        self.date_TA = QtWidgets.QFrame(parent=self.content_container_TA)
        self.date_TA.setGeometry(QtCore.QRect(10, 10, 71, 61))
        self.date_TA.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.date_TA.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.date_TA.setObjectName("date_TA")
        self.day = QtWidgets.QLabel(parent=self.date_TA)
        self.day.setGeometry(QtCore.QRect(30, 10, 16, 21))
        self.day.setStyleSheet("border: none;\n"
"font-size: 22px")
        self.day.setObjectName("day")
        self.day_2 = QtWidgets.QLabel(parent=self.date_TA)
        self.day_2.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.day_2.setStyleSheet("border: none;\n"
"font-size: 20px")
        self.day_2.setObjectName("day_2")
        self.patient_name_TA = QtWidgets.QLabel(parent=self.content_container_TA)
        self.patient_name_TA.setGeometry(QtCore.QRect(89, 10, 161, 41))
        self.patient_name_TA.setStyleSheet("color: #15173D;\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"border: none;")
        self.patient_name_TA.setObjectName("patient_name_TA")
        self.time_TA = QtWidgets.QLabel(parent=self.content_container_TA)
        self.time_TA.setGeometry(QtCore.QRect(90, 50, 51, 21))
        self.time_TA.setStyleSheet("color: #15173D;\n"
"font-size: 12px;\n"
"border: none;")
        self.time_TA.setObjectName("time_TA")
        self.purpose_TA = QtWidgets.QLabel(parent=self.content_container_TA)
        self.purpose_TA.setGeometry(QtCore.QRect(140, 50, 111, 21))
        self.purpose_TA.setStyleSheet("color: #15173D;\n"
"font-size: 12px;\n"
"border: none;")
        self.purpose_TA.setObjectName("purpose_TA")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame_3)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 100, 941, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.total_patient = QtWidgets.QFrame(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_patient.sizePolicy().hasHeightForWidth())
        self.total_patient.setSizePolicy(sizePolicy)
        self.total_patient.setMinimumSize(QtCore.QSize(200, 99))
        self.total_patient.setMaximumSize(QtCore.QSize(200, 130))
        self.total_patient.setStyleSheet("background-color: rgb(21, 23, 61); border-radius: 15px;")
        self.total_patient.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.total_patient.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.total_patient.setObjectName("total_patient")
        self.total_patient_label = QtWidgets.QLabel(parent=self.total_patient)
        self.total_patient_label.setGeometry(QtCore.QRect(10, 10, 111, 21))
        self.total_patient_label.setStyleSheet("color: rgb(241, 233, 233);\n"
"font-size: 15px;\n"
"font-weight: bold;\n"
"border: none;")
        self.total_patient_label.setObjectName("total_patient_label")
        self.total_patient_label_2 = QtWidgets.QLabel(parent=self.total_patient)
        self.total_patient_label_2.setGeometry(QtCore.QRect(30, 40, 91, 41))
        self.total_patient_label_2.setStyleSheet("color: rgb(241, 233, 233);\n"
"font-size: 40px;\n"
"border: none;")
        self.total_patient_label_2.setObjectName("total_patient_label_2")
        self.gridLayout.addWidget(self.total_patient, 0, 0, 1, 1)
        self.upcomingApp = QtWidgets.QFrame(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upcomingApp.sizePolicy().hasHeightForWidth())
        self.upcomingApp.setSizePolicy(sizePolicy)
        self.upcomingApp.setMinimumSize(QtCore.QSize(200, 99))
        self.upcomingApp.setMaximumSize(QtCore.QSize(200, 130))
        self.upcomingApp.setStyleSheet("background-color: rgb(236, 198, 220); border-radius: 15px;\n"
"border: 1px solid rgb(150, 128, 156);")
        self.upcomingApp.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.upcomingApp.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.upcomingApp.setObjectName("upcomingApp")
        self.upcoming_app_label = QtWidgets.QLabel(parent=self.upcomingApp)
        self.upcoming_app_label.setGeometry(QtCore.QRect(10, 10, 167, 20))
        self.upcoming_app_label.setStyleSheet("color: #15173D;\n"
"font-size: 15px;\n"
"border: none;")
        self.upcoming_app_label.setObjectName("upcoming_app_label")
        self.total_patient_label_3 = QtWidgets.QLabel(parent=self.upcomingApp)
        self.total_patient_label_3.setGeometry(QtCore.QRect(10, 40, 91, 41))
        self.total_patient_label_3.setStyleSheet("color: #15173D;\n"
"font-size: 40px;\n"
"border: none;")
        self.total_patient_label_3.setObjectName("total_patient_label_3")
        self.gridLayout.addWidget(self.upcomingApp, 0, 1, 1, 1)
        self.prenatalVisit = QtWidgets.QFrame(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prenatalVisit.sizePolicy().hasHeightForWidth())
        self.prenatalVisit.setSizePolicy(sizePolicy)
        self.prenatalVisit.setMinimumSize(QtCore.QSize(200, 99))
        self.prenatalVisit.setMaximumSize(QtCore.QSize(200, 130))
        self.prenatalVisit.setStyleSheet("background-color: rgb(236, 198, 220); border-radius: 15px;\n"
"border: 1px solid rgb(150, 128, 156);")
        self.prenatalVisit.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.prenatalVisit.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.prenatalVisit.setObjectName("prenatalVisit")
        self.prenatal_visit_label = QtWidgets.QLabel(parent=self.prenatalVisit)
        self.prenatal_visit_label.setGeometry(QtCore.QRect(20, 10, 171, 21))
        self.prenatal_visit_label.setStyleSheet("color: #15173D;\n"
"font-size: 15px;\n"
"border: none;")
        self.prenatal_visit_label.setObjectName("prenatal_visit_label")
        self.total_patient_label_4 = QtWidgets.QLabel(parent=self.prenatalVisit)
        self.total_patient_label_4.setGeometry(QtCore.QRect(20, 40, 91, 41))
        self.total_patient_label_4.setStyleSheet("color: #15173D;\n"
"font-size: 40px;\n"
"border: none;")
        self.total_patient_label_4.setObjectName("total_patient_label_4")
        self.gridLayout.addWidget(self.prenatalVisit, 0, 2, 1, 1)
        self.Deliveries = QtWidgets.QFrame(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Deliveries.sizePolicy().hasHeightForWidth())
        self.Deliveries.setSizePolicy(sizePolicy)
        self.Deliveries.setMinimumSize(QtCore.QSize(200, 99))
        self.Deliveries.setMaximumSize(QtCore.QSize(200, 130))
        self.Deliveries.setStyleSheet("background-color: rgb(236, 198, 220); border-radius: 15px;\n"
"border: 1px solid rgb(150, 128, 156);")
        self.Deliveries.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Deliveries.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Deliveries.setObjectName("Deliveries")
        self.delivery_label = QtWidgets.QLabel(parent=self.Deliveries)
        self.delivery_label.setGeometry(QtCore.QRect(20, 10, 171, 21))
        self.delivery_label.setStyleSheet("color: #15173D;\n"
"font-size: 15px;\n"
"border: none;")
        self.delivery_label.setObjectName("delivery_label")
        self.total_patient_label_5 = QtWidgets.QLabel(parent=self.Deliveries)
        self.total_patient_label_5.setGeometry(QtCore.QRect(20, 40, 91, 41))
        self.total_patient_label_5.setMaximumSize(QtCore.QSize(200, 200))
        self.total_patient_label_5.setStyleSheet("color: #15173D;\n"
"font-size: 40px;\n"
"border: none;")
        self.total_patient_label_5.setObjectName("total_patient_label_5")
        self.gridLayout.addWidget(self.Deliveries, 0, 3, 1, 1)
        self.frame_3.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1224, 22))
        self.menubar.setObjectName("menubar")
        self.menuAppointments = QtWidgets.QMenu(parent=self.menubar)
        self.menuAppointments.setObjectName("menuAppointments")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMaternaDB = QtGui.QAction(parent=MainWindow)
        self.actionMaternaDB.setObjectName("actionMaternaDB")
        self.menubar.addAction(self.menuAppointments.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_2.setText(_translate("MainWindow", "Patient Records"))
        self.pushButton_3.setText(_translate("MainWindow", "Prenatal Care"))
        self.pushButton_4.setText(_translate("MainWindow", "Appointments        "))
        self.pushButton_5.setText(_translate("MainWindow", "Log out"))
        self.label_2.setText(_translate("MainWindow", "MATERNADB"))
        self.logo.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "DASHBOARD"))
        item = self.patient_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.patient_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NAME"))
        item = self.patient_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TYPE"))
        item = self.patient_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "REGISTERED"))
        self.label_3.setText(_translate("MainWindow", "Recent Patients"))
        self.Todays_appointment_TA.setText(_translate("MainWindow", "Today\'s Appointments"))
        self.day.setText(_translate("MainWindow", "5"))
        self.day_2.setText(_translate("MainWindow", "Jun"))
        self.patient_name_TA.setText(_translate("MainWindow", "Kaleil Jay O. Batumbakal"))
        self.time_TA.setText(_translate("MainWindow", "9:00AM"))
        self.purpose_TA.setText(_translate("MainWindow", "Prenatal Checkup"))
        self.total_patient_label.setText(_translate("MainWindow", "Total Patients"))
        self.total_patient_label_2.setText(_translate("MainWindow", "0"))
        self.upcoming_app_label.setText(_translate("MainWindow", "Upcoming Appointments"))
        self.total_patient_label_3.setText(_translate("MainWindow", "0"))
        self.prenatal_visit_label.setText(_translate("MainWindow", "Prenatal Visits"))
        self.total_patient_label_4.setText(_translate("MainWindow", "0"))
        self.delivery_label.setText(_translate("MainWindow", "Deliveries"))
        self.total_patient_label_5.setText(_translate("MainWindow", "0"))
        self.menuAppointments.setTitle(_translate("MainWindow", "MaternaDB"))
        self.actionMaternaDB.setText(_translate("MainWindow", "MaternaDB"))
