# Form implementation generated from reading ui file 'Ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(241, 233, 233);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.log_inFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.log_inFrame.setGeometry(QtCore.QRect(350, 70, 341, 381))
        self.log_inFrame.setStyleSheet("border-radius:30px;\n"
"background-color: rgb(178, 100, 168); border-radius: 5px;")
        self.log_inFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.log_inFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.log_inFrame.setObjectName("log_inFrame")
        self.label = QtWidgets.QLabel(parent=self.log_inFrame)
        self.label.setGeometry(QtCore.QRect(150, 80, 49, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.log_inFrame)
        self.label_2.setGeometry(QtCore.QRect(130, 110, 161, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.log_inFrame)
        self.label_3.setGeometry(QtCore.QRect(40, 150, 49, 16))
        self.label_3.setObjectName("label_3")
        self.EmailInput = QtWidgets.QLineEdit(parent=self.log_inFrame)
        self.EmailInput.setGeometry(QtCore.QRect(40, 170, 261, 31))
        self.EmailInput.setStyleSheet("background-color: rgb(247, 247, 247); border-radius: 5px;")
        self.EmailInput.setText("")
        self.EmailInput.setObjectName("EmailInput")
        self.label_4 = QtWidgets.QLabel(parent=self.log_inFrame)
        self.label_4.setGeometry(QtCore.QRect(40, 210, 51, 16))
        self.label_4.setObjectName("label_4")
        self.PasswordInput = QtWidgets.QLineEdit(parent=self.log_inFrame)
        self.PasswordInput.setGeometry(QtCore.QRect(40, 230, 261, 31))
        self.PasswordInput.setStyleSheet("background-color: rgb(247, 247, 247); border-radius: 5px;")
        self.PasswordInput.setText("")
        self.PasswordInput.setObjectName("PasswordInput")
        self.checkBox = QtWidgets.QCheckBox(parent=self.log_inFrame)
        self.checkBox.setGeometry(QtCore.QRect(40, 270, 101, 20))
        self.checkBox.setObjectName("checkBox")
        self.signupButton = QtWidgets.QPushButton(parent=self.log_inFrame)
        self.signupButton.setGeometry(QtCore.QRect(40, 300, 75, 24))
        self.signupButton.setStyleSheet("background-color: rgb(21, 23, 61); border-radius: 5px;\n"
"color: rgb(247, 247, 247);")
        self.signupButton.setCheckable(True)
        self.signupButton.setObjectName("signupButton")
        self.signinButton = QtWidgets.QPushButton(parent=self.log_inFrame)
        self.signinButton.setGeometry(QtCore.QRect(230, 300, 75, 24))
        self.signinButton.setStyleSheet("background-color: rgb(21, 23, 61);border-radius: 5px;\n"
"color: rgb(247, 247, 247);")
        self.signinButton.setCheckable(True)
        self.signinButton.setObjectName("signinButton")
        self.forgotButton = QtWidgets.QPushButton(parent=self.log_inFrame)
        self.forgotButton.setGeometry(QtCore.QRect(214, 270, 91, 24))
        self.forgotButton.setCheckable(True)
        self.forgotButton.setObjectName("forgotButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "LOGO"))
        self.label_2.setText(_translate("MainWindow", "Welcome Back!"))
        self.label_3.setText(_translate("MainWindow", "Email"))
        self.label_4.setText(_translate("MainWindow", "Password"))
        self.checkBox.setText(_translate("MainWindow", "Remember me"))
        self.signupButton.setText(_translate("MainWindow", "Sign up"))
        self.signinButton.setText(_translate("MainWindow", "Sign in"))
        self.forgotButton.setText(_translate("MainWindow", "Forgot password"))
