# Form implementation generated from reading ui file 'Ui/medical_history.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1301, 864)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 60, 231, 761))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: rgb(192, 116, 182)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 180, 191, 41))
        self.pushButton.setStyleSheet("background-color: rgb(240, 230, 240);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 230, 191, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(240, 230, 240);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 280, 191, 41))
        self.pushButton_3.setStyleSheet("background-color: rgb(240, 230, 240);\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 330, 191, 41))
        self.pushButton_4.setStyleSheet("background-color: rgb(240, 230, 240);\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 500, 191, 41))
        self.pushButton_5.setStyleSheet("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1341, 61))
        self.frame_2.setStyleSheet("background-color: rgb(26, 26, 62)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(130, 0, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 100, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(230, 60, 1071, 761))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("background-color: rgb(240, 230, 240)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setGeometry(QtCore.QRect(40, 20, 371, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(40, 80, 1001, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(26, 26, 62);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(20, 20, 111, 91))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.patient_name = QtWidgets.QLabel(parent=self.frame_4)
        self.patient_name.setGeometry(QtCore.QRect(170, 30, 411, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patient_name.sizePolicy().hasHeightForWidth())
        self.patient_name.setSizePolicy(sizePolicy)
        self.patient_name.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 20px")
        self.patient_name.setObjectName("patient_name")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame_4)
        self.layoutWidget.setGeometry(QtCore.QRect(170, 60, 591, 52))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.patient_id_label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.patient_id_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.patient_id_label.setObjectName("patient_id_label")
        self.gridLayout.addWidget(self.patient_id_label, 0, 0, 1, 1)
        self.placeholder_p_ID = QtWidgets.QLabel(parent=self.layoutWidget)
        self.placeholder_p_ID.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.placeholder_p_ID.setObjectName("placeholder_p_ID")
        self.gridLayout.addWidget(self.placeholder_p_ID, 0, 1, 1, 1)
        self.patient_id_label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.patient_id_label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.patient_id_label_2.setObjectName("patient_id_label_2")
        self.gridLayout.addWidget(self.patient_id_label_2, 1, 0, 1, 1)
        self.placeholder_p_bloodType = QtWidgets.QLabel(parent=self.layoutWidget)
        self.placeholder_p_bloodType.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.placeholder_p_bloodType.setObjectName("placeholder_p_bloodType")
        self.gridLayout.addWidget(self.placeholder_p_bloodType, 1, 1, 1, 1)
        self.patient_id_label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.patient_id_label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.patient_id_label_4.setObjectName("patient_id_label_4")
        self.gridLayout.addWidget(self.patient_id_label_4, 1, 2, 1, 1)
        self.placeholder_philhealth_num = QtWidgets.QLabel(parent=self.layoutWidget)
        self.placeholder_philhealth_num.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.placeholder_philhealth_num.setObjectName("placeholder_philhealth_num")
        self.gridLayout.addWidget(self.placeholder_philhealth_num, 1, 3, 1, 3)
        self.patient_id_label_5 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.patient_id_label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.patient_id_label_5.setObjectName("patient_id_label_5")
        self.gridLayout.addWidget(self.patient_id_label_5, 0, 2, 1, 1)
        self.placeholder_register_date = QtWidgets.QLabel(parent=self.layoutWidget)
        self.placeholder_register_date.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.placeholder_register_date.setObjectName("placeholder_register_date")
        self.gridLayout.addWidget(self.placeholder_register_date, 0, 3, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.frame_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 240, 803, 40))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54;\n"
"}\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54;\n"
"}\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54;\n"
"}\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54;\n"
"}\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setChecked(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54;\n"
"}\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54;\n"
"}\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout.addWidget(self.pushButton_11)
        self.left = QtWidgets.QFrame(parent=self.frame_3)
        self.left.setGeometry(QtCore.QRect(40, 340, 991, 381))
        self.left.setStyleSheet("background-color:rgb(236, 198, 220);\n"
"border: 1px solid rgb(158, 136, 163);\n"
"border-radius: 15px;")
        self.left.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.left.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.left.setObjectName("left")
        self.medical_history_table = QtWidgets.QTableWidget(parent=self.left)
        self.medical_history_table.setGeometry(QtCore.QRect(0, 0, 991, 381))
        self.medical_history_table.setAutoFillBackground(True)
        self.medical_history_table.setStyleSheet("QTableWidget {\n"
"    background-color:rgb(236, 198, 220);\n"
"    border: 1px solid rgb(158, 136, 163);\n"
"    border-radius: 15px;\n"
"}\n"
"QTableWidget::item {\n"
"    background-color: rgb(236, 198, 220);\n"
"    color: rgb(21, 23, 61);\n"
"    padding: 8px;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(210, 177, 200);\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: rgb(192, 116, 182);\n"
"    color: white;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: rgb(236, 198, 220);\n"
"    color: rgb(21, 23, 61);\n"
"    font-weight: bold;\n"
"    font-size: 10px;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(155, 132, 160);\n"
"    padding: 5px;\n"
"}\n"
"QScrollBar:vertical {\n"
"    background: white;\n"
"    width: 6px;\n"
"    border-radius: 3px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(178, 100, 168);\n"
"    border-radius: 3px;\n"
"}")
        self.medical_history_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.medical_history_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.medical_history_table.setAlternatingRowColors(False)
        self.medical_history_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.medical_history_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.medical_history_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.medical_history_table.setShowGrid(False)
        self.medical_history_table.setColumnCount(4)
        self.medical_history_table.setObjectName("medical_history_table")
        self.medical_history_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.medical_history_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.medical_history_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.medical_history_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.medical_history_table.setHorizontalHeaderItem(3, item)
        self.medical_history_table.horizontalHeader().setCascadingSectionResizes(False)
        self.medical_history_table.horizontalHeader().setDefaultSectionSize(200)
        self.medical_history_table.horizontalHeader().setHighlightSections(True)
        self.medical_history_table.horizontalHeader().setMinimumSectionSize(32)
        self.medical_history_table.horizontalHeader().setSortIndicatorShown(False)
        self.medical_history_table.horizontalHeader().setStretchLastSection(True)
        self.medical_history_table.verticalHeader().setVisible(False)
        self.medical_history_table.verticalHeader().setCascadingSectionResizes(False)
        self.medical_history_table.verticalHeader().setDefaultSectionSize(40)
        self.add_condition_btn = QtWidgets.QPushButton(parent=self.frame_3)
        self.add_condition_btn.setGeometry(QtCore.QRect(40, 300, 121, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_condition_btn.sizePolicy().hasHeightForWidth())
        self.add_condition_btn.setSizePolicy(sizePolicy)
        self.add_condition_btn.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(192, 116, 182);\n"
"color: white;\n"
"border: 1px solid rgb(158, 136, 163);")
        self.add_condition_btn.setObjectName("add_condition_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1301, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_2.setText(_translate("MainWindow", "Patient Records"))
        self.pushButton_3.setText(_translate("MainWindow", "Prenatal Care"))
        self.pushButton_4.setText(_translate("MainWindow", "Appointments"))
        self.pushButton_5.setText(_translate("MainWindow", "Log out"))
        self.label_2.setText(_translate("MainWindow", "MATERNADB"))
        self.label_3.setText(_translate("MainWindow", "LOGO"))
        self.label.setText(_translate("MainWindow", "Medical History"))
        self.patient_name.setText(_translate("MainWindow", "Emily Santos"))

        self.patient_id_label.setText(_translate("MainWindow", "Patient ID:"))
        self.placeholder_p_ID.setText(_translate("MainWindow", "P-10234"))
        self.patient_id_label_2.setText(_translate("MainWindow", "Blood Type:"))
        self.placeholder_p_bloodType.setText(_translate("MainWindow", "O+"))
        self.patient_id_label_4.setText(_translate("MainWindow", "PhilHealth#:"))
        self.placeholder_philhealth_num.setText(_translate("MainWindow", "1234-5678-9012"))
        self.patient_id_label_5.setText(_translate("MainWindow", "Registered:"))
        self.placeholder_register_date.setText(_translate("MainWindow", "01/15/2023"))
        self.pushButton_6.setText(_translate("MainWindow", "Patient Profile"))
        self.pushButton_7.setText(_translate("MainWindow", "Past Pregnancy"))
        self.pushButton_8.setText(_translate("MainWindow", "Prescriptions"))
        self.pushButton_9.setText(_translate("MainWindow", "Medical History"))
        self.pushButton_10.setText(_translate("MainWindow", "Family Planning"))
        self.pushButton_11.setText(_translate("MainWindow", "Appointments"))
        item = self.medical_history_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "CONDITION"))
        item = self.medical_history_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DIAGNOSED DATE"))
        item = self.medical_history_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "STATUS"))
        item = self.medical_history_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "NOTES"))
        self.add_condition_btn.setText(_translate("MainWindow", "+ Add Condition"))
