# Form implementation generated from reading ui file 'Ui/past_pregnancy.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1230, 835)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 60, 231, 741))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet(" background-color: rgb(192, 116, 182)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 180, 191, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("background-color: rgb(240, 230, 240);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 230, 191, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("background-color: rgb(240, 230, 240);\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 280, 191, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setStyleSheet("background-color: rgb(240, 230, 240);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 330, 191, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setStyleSheet("background-color: rgb(240, 230, 240);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 500, 191, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1231, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(26, 26, 62)\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(130, 0, 91, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 100, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(230, 60, 1001, 761))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("background-color: rgb(240, 230, 240)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setGeometry(QtCore.QRect(40, 20, 401, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(40, 80, 921, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(26, 26, 62);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(20, 20, 111, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.name_acronym = QtWidgets.QLabel(parent=self.frame_5)
        self.name_acronym.setGeometry(QtCore.QRect(30, 40, 49, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_acronym.sizePolicy().hasHeightForWidth())
        self.name_acronym.setSizePolicy(sizePolicy)
        self.name_acronym.setObjectName("name_acronym")
        self.patient_name = QtWidgets.QLabel(parent=self.frame_4)
        self.patient_name.setGeometry(QtCore.QRect(170, 30, 411, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patient_name.sizePolicy().hasHeightForWidth())
        self.patient_name.setSizePolicy(sizePolicy)
        self.patient_name.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 20px")
        self.patient_name.setObjectName("patient_name")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.frame_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(170, 60, 578, 52))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layoutWidget_2.sizePolicy().hasHeightForWidth())
        self.layoutWidget_2.setSizePolicy(sizePolicy)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.patient_id_label = QtWidgets.QLabel(parent=self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patient_id_label.sizePolicy().hasHeightForWidth())
        self.patient_id_label.setSizePolicy(sizePolicy)
        self.patient_id_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.patient_id_label.setObjectName("patient_id_label")
        self.gridLayout_4.addWidget(self.patient_id_label, 0, 0, 1, 1)
        self.placeholder_p_ID = QtWidgets.QLabel(parent=self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.placeholder_p_ID.sizePolicy().hasHeightForWidth())
        self.placeholder_p_ID.setSizePolicy(sizePolicy)
        self.placeholder_p_ID.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.placeholder_p_ID.setObjectName("placeholder_p_ID")
        self.gridLayout_4.addWidget(self.placeholder_p_ID, 0, 1, 1, 2)
        self.age_label = QtWidgets.QLabel(parent=self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.age_label.sizePolicy().hasHeightForWidth())
        self.age_label.setSizePolicy(sizePolicy)
        self.age_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.age_label.setObjectName("age_label")
        self.gridLayout_4.addWidget(self.age_label, 0, 3, 1, 1)
        self.age_placeholder = QtWidgets.QLabel(parent=self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.age_placeholder.sizePolicy().hasHeightForWidth())
        self.age_placeholder.setSizePolicy(sizePolicy)
        self.age_placeholder.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.age_placeholder.setObjectName("age_placeholder")
        self.gridLayout_4.addWidget(self.age_placeholder, 0, 4, 1, 1)
        self.registered_date = QtWidgets.QLabel(parent=self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registered_date.sizePolicy().hasHeightForWidth())
        self.registered_date.setSizePolicy(sizePolicy)
        self.registered_date.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.registered_date.setObjectName("registered_date")
        self.gridLayout_4.addWidget(self.registered_date, 0, 5, 1, 1)
        self.registered_data_data = QtWidgets.QLabel(parent=self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registered_data_data.sizePolicy().hasHeightForWidth())
        self.registered_data_data.setSizePolicy(sizePolicy)
        self.registered_data_data.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.registered_data_data.setObjectName("registered_data_data")
        self.gridLayout_4.addWidget(self.registered_data_data, 0, 6, 1, 1)
        self.blood_type_label = QtWidgets.QLabel(parent=self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blood_type_label.sizePolicy().hasHeightForWidth())
        self.blood_type_label.setSizePolicy(sizePolicy)
        self.blood_type_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.blood_type_label.setObjectName("blood_type_label")
        self.gridLayout_4.addWidget(self.blood_type_label, 1, 0, 1, 2)
        self.placeholder_p_bloodType = QtWidgets.QLabel(parent=self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.placeholder_p_bloodType.sizePolicy().hasHeightForWidth())
        self.placeholder_p_bloodType.setSizePolicy(sizePolicy)
        self.placeholder_p_bloodType.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.placeholder_p_bloodType.setObjectName("placeholder_p_bloodType")
        self.gridLayout_4.addWidget(self.placeholder_p_bloodType, 1, 2, 1, 1)
        self.philhealth_number = QtWidgets.QLabel(parent=self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.philhealth_number.sizePolicy().hasHeightForWidth())
        self.philhealth_number.setSizePolicy(sizePolicy)
        self.philhealth_number.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.philhealth_number.setObjectName("philhealth_number")
        self.gridLayout_4.addWidget(self.philhealth_number, 1, 3, 1, 1)
        self.philhealth_placeholder = QtWidgets.QLabel(parent=self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.philhealth_placeholder.sizePolicy().hasHeightForWidth())
        self.philhealth_placeholder.setSizePolicy(sizePolicy)
        self.philhealth_placeholder.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.philhealth_placeholder.setObjectName("philhealth_placeholder")
        self.gridLayout_4.addWidget(self.philhealth_placeholder, 1, 4, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame_3)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 240, 797, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layoutWidget.sizePolicy().hasHeightForWidth())
        self.layoutWidget.setSizePolicy(sizePolicy)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.pushButton_6.setChecked(True)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54; /* underline */\n"
"}\n"
"\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setChecked(True)
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
        "    background: transparent;\n"
        "    border: none;\n"
        "    padding: 8px 18px;\n"
        "    color: rgb(26, 26, 62);\n"
        "    font-size: 14px;\n"
        "    font-weight: bold;\n"
        "}\n"
        "\n"
        "QPushButton:hover {\n"
        "    color: #000;\n"
        "}\n"
        "\n"
        "QPushButton:checked {\n"
        "    color: #1a1a1a;\n"
        "    border-bottom: 3px solid #2c2c54;\n"
        "}\n"
        "\n"
        "QPushButton:!checked {\n"
        "    border-bottom: 3px solid transparent;\n"
        "}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54; /* underline */\n"
"}\n"
"\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54; /* underline */\n"
"}\n"
"\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54; /* underline */\n"
"}\n"
"\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54; /* underline */\n"
"}\n"
"\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout.addWidget(self.pushButton_11)
        self.patient_table = QtWidgets.QTableWidget(parent=self.frame_3)
        self.patient_table.setGeometry(QtCore.QRect(40, 330, 921, 371))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patient_table.sizePolicy().hasHeightForWidth())
        self.patient_table.setSizePolicy(sizePolicy)
        self.patient_table.setAutoFillBackground(True)
        self.patient_table.setStyleSheet("QTableWidget {\n"
"    background-color:rgb(236, 198, 220);\n"
"    border: 1px solid rgb(158, 136, 163);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    background-color: rgb(236, 198, 220);\n"
"    color: rgb(21, 23, 61);\n"
"    padding: 8px;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(210, 177, 200);\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: black;\n"
"    color: rgb(21, 23, 61);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(236, 198, 220);\n"
"    color: rgb(21, 23, 61);\n"
"    font-weight: bold;\n"
"    font-size: 10px;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(155, 132, 160);\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: white;\n"
"    width: 6px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(178, 100, 168);\n"
"    border-radius: 3px;\n"
"}")
        self.patient_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.patient_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.patient_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.patient_table.setAlternatingRowColors(False)
        self.patient_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.patient_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.patient_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.patient_table.setShowGrid(False)
        self.patient_table.setColumnCount(6)
        self.patient_table.setObjectName("patient_table")
        self.patient_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setHorizontalHeaderItem(5, item)
        self.patient_table.horizontalHeader().setCascadingSectionResizes(False)
        self.patient_table.horizontalHeader().setDefaultSectionSize(150)
        self.patient_table.horizontalHeader().setHighlightSections(True)
        self.patient_table.horizontalHeader().setMinimumSectionSize(32)
        self.patient_table.horizontalHeader().setSortIndicatorShown(False)
        self.patient_table.horizontalHeader().setStretchLastSection(True)
        self.patient_table.verticalHeader().setVisible(False)
        self.patient_table.verticalHeader().setCascadingSectionResizes(False)
        self.patient_table.verticalHeader().setDefaultSectionSize(40)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.frame_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 290, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layoutWidget1.sizePolicy().hasHeightForWidth())
        self.layoutWidget1.setSizePolicy(sizePolicy)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gravida_label = QtWidgets.QLabel(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gravida_label.sizePolicy().hasHeightForWidth())
        self.gravida_label.setSizePolicy(sizePolicy)
        self.gravida_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.gravida_label.setObjectName("gravida_label")
        self.horizontalLayout_2.addWidget(self.gravida_label)
        self.gravida_placeholer = QtWidgets.QLabel(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gravida_placeholer.sizePolicy().hasHeightForWidth())
        self.gravida_placeholer.setSizePolicy(sizePolicy)
        self.gravida_placeholer.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"font-weight: bold;")
        self.gravida_placeholer.setObjectName("gravida_placeholer")
        self.horizontalLayout_2.addWidget(self.gravida_placeholer)
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.frame_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(150, 290, 58, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layoutWidget2.sizePolicy().hasHeightForWidth())
        self.layoutWidget2.setSizePolicy(sizePolicy)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.para_label = QtWidgets.QLabel(parent=self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.para_label.sizePolicy().hasHeightForWidth())
        self.para_label.setSizePolicy(sizePolicy)
        self.para_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.para_label.setObjectName("para_label")
        self.horizontalLayout_3.addWidget(self.para_label)
        self.para_placeholder = QtWidgets.QLabel(parent=self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.para_placeholder.sizePolicy().hasHeightForWidth())
        self.para_placeholder.setSizePolicy(sizePolicy)
        self.para_placeholder.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"font-weight: bold;")
        self.para_placeholder.setObjectName("para_placeholder")
        self.horizontalLayout_3.addWidget(self.para_placeholder)
        self.layoutWidget3 = QtWidgets.QWidget(parent=self.frame_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(220, 290, 90, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layoutWidget3.sizePolicy().hasHeightForWidth())
        self.layoutWidget3.setSizePolicy(sizePolicy)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.abortion_label = QtWidgets.QLabel(parent=self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abortion_label.sizePolicy().hasHeightForWidth())
        self.abortion_label.setSizePolicy(sizePolicy)
        self.abortion_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.abortion_label.setObjectName("abortion_label")
        self.horizontalLayout_4.addWidget(self.abortion_label)
        self.abortion_placeholder = QtWidgets.QLabel(parent=self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abortion_placeholder.sizePolicy().hasHeightForWidth())
        self.abortion_placeholder.setSizePolicy(sizePolicy)
        self.abortion_placeholder.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"font-weight: bold;")
        self.abortion_placeholder.setObjectName("abortion_placeholder")
        self.horizontalLayout_4.addWidget(self.abortion_placeholder)
        self.layoutWidget4 = QtWidgets.QWidget(parent=self.frame_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(320, 290, 131, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layoutWidget4.sizePolicy().hasHeightForWidth())
        self.layoutWidget4.setSizePolicy(sizePolicy)
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.living_children_placeholder = QtWidgets.QLabel(parent=self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.living_children_placeholder.sizePolicy().hasHeightForWidth())
        self.living_children_placeholder.setSizePolicy(sizePolicy)
        self.living_children_placeholder.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"font-weight: bold;")
        self.living_children_placeholder.setObjectName("living_children_placeholder")
        self.horizontalLayout_5.addWidget(self.living_children_placeholder)
        self.add_btn = QtWidgets.QPushButton(parent=self.frame_3)
        self.add_btn.setGeometry(QtCore.QRect(720, 290, 111, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_btn.sizePolicy().hasHeightForWidth())
        self.add_btn.setSizePolicy(sizePolicy)
        self.add_btn.setStyleSheet("background-color: rgb(236, 198, 220);\n"
"border-radius: 15px;")
        self.add_btn.setObjectName("add_btn")
        self.remove_btn = QtWidgets.QPushButton(parent=self.frame_3)
        self.remove_btn.setGeometry(QtCore.QRect(850, 290, 111, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_btn.sizePolicy().hasHeightForWidth())
        self.remove_btn.setSizePolicy(sizePolicy)
        self.remove_btn.setStyleSheet("background-color: rgb(236, 198, 220);\n"
"border-radius: 15px;")
        self.remove_btn.setObjectName("remove_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1230, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_2.setText(_translate("MainWindow", "Patient Records"))
        self.pushButton_3.setText(_translate("MainWindow", "Prenatal Care"))
        self.pushButton_4.setText(_translate("MainWindow", "        Appointments        "))
        self.pushButton_5.setText(_translate("MainWindow", "Log out"))
        self.label_2.setText(_translate("MainWindow", "MATERNADB"))
        self.label_3.setText(_translate("MainWindow", "LOGO"))
        self.label.setText(_translate("MainWindow", "Patient Records"))
        self.name_acronym.setText(_translate("MainWindow", "TextLabel"))
        self.patient_name.setText(_translate("MainWindow", "NAME"))
        self.patient_id_label.setText(_translate("MainWindow", "Patient ID:"))
        self.placeholder_p_ID.setText(_translate("MainWindow", "placeholder"))
        self.age_label.setText(_translate("MainWindow", "Age:"))
        self.age_placeholder.setText(_translate("MainWindow", "null"))
        self.registered_date.setText(_translate("MainWindow", "Registered:"))
        self.registered_data_data.setText(_translate("MainWindow", "MM/DD/YYYY"))
        self.blood_type_label.setText(_translate("MainWindow", "Blood Type:"))
        self.placeholder_p_bloodType.setText(_translate("MainWindow", "placeholder"))
        self.philhealth_number.setText(_translate("MainWindow", "PhilHealth#:"))
        self.philhealth_placeholder.setText(_translate("MainWindow", "1234-5676-8907"))
        self.pushButton_6.setText(_translate("MainWindow", "Patient Profile"))
        self.pushButton_7.setText(_translate("MainWindow", "Past Pregnancy"))
        self.pushButton_8.setText(_translate("MainWindow", "Prescriptions"))
        self.pushButton_9.setText(_translate("MainWindow", "Medical History"))
        self.pushButton_10.setText(_translate("MainWindow", "Family Planning"))
        self.pushButton_11.setText(_translate("MainWindow", "Appointments"))
        item = self.patient_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "#0001"))
        item = self.patient_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DELIVERY DATE"))
        item = self.patient_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "OUTCOME"))
        item = self.patient_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DELIVERY TYPE"))
        item = self.patient_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "BABY WEIGHT"))
        item = self.patient_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ACTION"))
        self.gravida_label.setText(_translate("MainWindow", "GRAVIDA:"))
        self.gravida_placeholer.setText(_translate("MainWindow", "ph"))
        self.para_label.setText(_translate("MainWindow", "PARA:"))
        self.para_placeholder.setText(_translate("MainWindow", "ph"))
        self.abortion_label.setText(_translate("MainWindow", "ABORTION:"))
        self.abortion_placeholder.setText(_translate("MainWindow", "ph"))
        self.label_7.setText(_translate("MainWindow", "LIVING CHILDREN:"))
        self.living_children_placeholder.setText(_translate("MainWindow", "ph"))
        self.add_btn.setText(_translate("MainWindow", "Add Pregnancy"))
        self.remove_btn.setText(_translate("MainWindow", "Remove Pregnancy"))
