# Form implementation generated from reading ui file 'Ui/patient_profile.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1230, 835)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 60, 231, 741))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet(" background-color: rgb(192, 116, 182)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 180, 191, 41))
        self.pushButton.setStyleSheet("background-color: rgb(240, 230, 240);\n"
"border-radius: 12px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 230, 221, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(240, 230, 240);\n"
"border-radius: 12px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 280, 191, 41))
        self.pushButton_3.setStyleSheet("background-color: rgb(240, 230, 240);\n"
"border-radius: 12px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 330, 191, 41))
        self.pushButton_4.setStyleSheet("background-color: rgb(240, 230, 240);\n"
"border-radius: 12px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 500, 191, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1231, 61))
        self.frame_2.setStyleSheet("background-color: rgb(26, 26, 62)\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(130, 0, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 100, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(230, 60, 1001, 761))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("background-color: rgb(240, 230, 240)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setGeometry(QtCore.QRect(40, 20, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.remove_patient_btn = QtWidgets.QPushButton(parent=self.frame_3)
        self.remove_patient_btn.setGeometry(QtCore.QRect(840, 270, 121, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_patient_btn.sizePolicy().hasHeightForWidth())
        self.remove_patient_btn.setSizePolicy(sizePolicy)
        self.remove_patient_btn.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(236, 198, 220);\n"
"border: 1px solid rgb(210, 177, 200);")
        self.remove_patient_btn.setObjectName("remove_patient_btn")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(40, 80, 921, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(26, 26, 62);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(20, 20, 111, 91))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.patient_name = QtWidgets.QLabel(parent=self.frame_4)
        self.patient_name.setGeometry(QtCore.QRect(170, 30, 411, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patient_name.sizePolicy().hasHeightForWidth())
        self.patient_name.setSizePolicy(sizePolicy)
        self.patient_name.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 20px")
        self.patient_name.setObjectName("patient_name")
        self.patient_id_label = QtWidgets.QLabel(parent=self.frame_4)
        self.patient_id_label.setGeometry(QtCore.QRect(170, 60, 71, 21))
        self.patient_id_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.patient_id_label.setObjectName("patient_id_label")
        self.patient_id_label_2 = QtWidgets.QLabel(parent=self.frame_4)
        self.patient_id_label_2.setGeometry(QtCore.QRect(170, 90, 91, 21))
        self.patient_id_label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.patient_id_label_2.setObjectName("patient_id_label_2")
        self.placeholder_p_ID = QtWidgets.QLabel(parent=self.frame_4)
        self.placeholder_p_ID.setGeometry(QtCore.QRect(250, 60, 101, 21))
        self.placeholder_p_ID.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.placeholder_p_ID.setObjectName("placeholder_p_ID")
        self.placeholder_p_bloodType = QtWidgets.QLabel(parent=self.frame_4)
        self.placeholder_p_bloodType.setGeometry(QtCore.QRect(260, 90, 101, 21))
        self.placeholder_p_bloodType.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.placeholder_p_bloodType.setObjectName("placeholder_p_bloodType")
        self.placeholder_register_date = QtWidgets.QLabel(parent=self.frame_4)
        self.placeholder_register_date.setGeometry(QtCore.QRect(480, 60, 101, 21))
        self.placeholder_register_date.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.placeholder_register_date.setObjectName("placeholder_register_date")
        self.patient_id_label_3 = QtWidgets.QLabel(parent=self.frame_4)
        self.patient_id_label_3.setGeometry(QtCore.QRect(390, 60, 81, 21))
        self.patient_id_label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.patient_id_label_3.setObjectName("patient_id_label_3")
        self.placeholder_philhealth_num = QtWidgets.QLabel(parent=self.frame_4)
        self.placeholder_philhealth_num.setGeometry(QtCore.QRect(480, 90, 131, 21))
        self.placeholder_philhealth_num.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.placeholder_philhealth_num.setObjectName("placeholder_philhealth_num")
        self.patient_id_label_4 = QtWidgets.QLabel(parent=self.frame_4)
        self.patient_id_label_4.setGeometry(QtCore.QRect(390, 90, 81, 21))
        self.patient_id_label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.patient_id_label_4.setObjectName("patient_id_label_4")
        self.next_btn = QtWidgets.QPushButton(parent=self.frame_4)
        self.next_btn.setGeometry(QtCore.QRect(770, 50, 111, 51))
        self.next_btn.setStyleSheet("background-color: rgb(240, 230, 240);\n"
"border-radius: 15px;")
        self.next_btn.setObjectName("next_btn")
        self.personal_information_frame = QtWidgets.QFrame(parent=self.frame_3)
        self.personal_information_frame.setGeometry(QtCore.QRect(40, 310, 921, 221))
        self.personal_information_frame.setStyleSheet("background-color: rgb(236, 198, 220);\n"
"border-radius: 15px;\n"
"border: 1px solid rgb(210, 177, 200);\n"
"")
        self.personal_information_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.personal_information_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.personal_information_frame.setObjectName("personal_information_frame")
        self.personalInformation_text = QtWidgets.QLabel(parent=self.personal_information_frame)
        self.personalInformation_text.setGeometry(QtCore.QRect(20, 10, 251, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.personalInformation_text.sizePolicy().hasHeightForWidth())
        self.personalInformation_text.setSizePolicy(sizePolicy)
        self.personalInformation_text.setStyleSheet("color: rgb(26, 26, 62);\n"
"font-size: 20px;\n"
"border: none;\n"
"font-weight: bold;")
        self.personalInformation_text.setObjectName("personalInformation_text")
        self.widget = QtWidgets.QWidget(parent=self.personal_information_frame)
        self.widget.setGeometry(QtCore.QRect(20, 40, 901, 164))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.last_name_placeholder_2 = QtWidgets.QLabel(parent=self.widget)
        self.last_name_placeholder_2.setStyleSheet("color: rgb(26, 26, 62);\n"
"border: none;\n"
"font-size: 16px")
        self.last_name_placeholder_2.setObjectName("last_name_placeholder_2")
        self.gridLayout.addWidget(self.last_name_placeholder_2, 0, 0, 1, 1)
        self.first_name_label = QtWidgets.QLabel(parent=self.widget)
        self.first_name_label.setStyleSheet("color: rgb(26, 26, 62);\n"
"border: none;\n"
"font-size: 16px")
        self.first_name_label.setObjectName("first_name_label")
        self.gridLayout.addWidget(self.first_name_label, 0, 1, 1, 1)
        self.middle_name_label = QtWidgets.QLabel(parent=self.widget)
        self.middle_name_label.setStyleSheet("color: rgb(26, 26, 62);\n"
"border: none;\n"
"font-size: 16px")
        self.middle_name_label.setObjectName("middle_name_label")
        self.gridLayout.addWidget(self.middle_name_label, 0, 2, 1, 1)
        self.last_name_placeholder = QtWidgets.QLabel(parent=self.widget)
        self.last_name_placeholder.setStyleSheet("border: none;\n"
"font-weight: bold;\n"
"color:rgb(26, 26, 62);\n"
"font-size: 16px")
        self.last_name_placeholder.setObjectName("last_name_placeholder")
        self.gridLayout.addWidget(self.last_name_placeholder, 1, 0, 1, 1)
        self.first_name_placeholder = QtWidgets.QLabel(parent=self.widget)
        self.first_name_placeholder.setStyleSheet("border: none;\n"
"font-weight: bold;\n"
"color:rgb(26, 26, 62);\n"
"font-size: 16px")
        self.first_name_placeholder.setObjectName("first_name_placeholder")
        self.gridLayout.addWidget(self.first_name_placeholder, 1, 1, 1, 1)
        self.middle_name_placeholder = QtWidgets.QLabel(parent=self.widget)
        self.middle_name_placeholder.setStyleSheet("border: none;\n"
"font-weight: bold;\n"
"color:rgb(26, 26, 62);\n"
"font-size: 16px")
        self.middle_name_placeholder.setObjectName("middle_name_placeholder")
        self.gridLayout.addWidget(self.middle_name_placeholder, 1, 2, 1, 1)
        self.date_of_birth_placeholder = QtWidgets.QLabel(parent=self.widget)
        self.date_of_birth_placeholder.setStyleSheet("color: rgb(26, 26, 62);\n"
"font-size: 16px;\n"
"border: none;")
        self.date_of_birth_placeholder.setObjectName("date_of_birth_placeholder")
        self.gridLayout.addWidget(self.date_of_birth_placeholder, 2, 0, 1, 1)
        self.civi_status_label = QtWidgets.QLabel(parent=self.widget)
        self.civi_status_label.setStyleSheet("color: rgb(26, 26, 62);\n"
"font-size: 16px;\n"
"border: none;")
        self.civi_status_label.setObjectName("civi_status_label")
        self.gridLayout.addWidget(self.civi_status_label, 2, 1, 1, 1)
        self.nationality_label = QtWidgets.QLabel(parent=self.widget)
        self.nationality_label.setStyleSheet("color: rgb(26, 26, 62);\n"
"font-size: 16px;\n"
"border: none;")
        self.nationality_label.setObjectName("nationality_label")
        self.gridLayout.addWidget(self.nationality_label, 2, 2, 1, 1)
        self.bday_placeholder = QtWidgets.QLabel(parent=self.widget)
        self.bday_placeholder.setStyleSheet("border: none;\n"
"font-weight: bold;\n"
"color: rgb(26, 26, 62);\n"
"font-size: 16px")
        self.bday_placeholder.setObjectName("bday_placeholder")
        self.gridLayout.addWidget(self.bday_placeholder, 3, 0, 1, 1)
        self.civil_status_placeholder = QtWidgets.QLabel(parent=self.widget)
        self.civil_status_placeholder.setStyleSheet("border: none;\n"
"font-weight: bold;\n"
"color: rgb(26, 26, 62);\n"
"font-size: 16px")
        self.civil_status_placeholder.setObjectName("civil_status_placeholder")
        self.gridLayout.addWidget(self.civil_status_placeholder, 3, 1, 1, 1)
        self.nationality_placeholder = QtWidgets.QLabel(parent=self.widget)
        self.nationality_placeholder.setStyleSheet("border: none;\n"
"font-weight: bold;\n"
"color: rgb(26, 26, 62);\n"
"font-size: 16px")
        self.nationality_placeholder.setObjectName("nationality_placeholder")
        self.gridLayout.addWidget(self.nationality_placeholder, 3, 2, 1, 1)
        self.religion_placeholder_2 = QtWidgets.QLabel(parent=self.widget)
        self.religion_placeholder_2.setStyleSheet("color: rgb(26, 26, 62);\n"
"font-size: 16px;\n"
"border: none;")
        self.religion_placeholder_2.setObjectName("religion_placeholder_2")
        self.gridLayout.addWidget(self.religion_placeholder_2, 4, 0, 1, 1)
        self.occupation_label = QtWidgets.QLabel(parent=self.widget)
        self.occupation_label.setStyleSheet("color: rgb(26, 26, 62);\n"
"font-size: 16px;\n"
"border: none;")
        self.occupation_label.setObjectName("occupation_label")
        self.gridLayout.addWidget(self.occupation_label, 4, 1, 1, 1)
        self.contact_number_label = QtWidgets.QLabel(parent=self.widget)
        self.contact_number_label.setStyleSheet("color: rgb(26, 26, 62);\n"
"font-size: 16px;\n"
"border: none;")
        self.contact_number_label.setObjectName("contact_number_label")
        self.gridLayout.addWidget(self.contact_number_label, 4, 2, 1, 1)
        self.religion_placeholder = QtWidgets.QLabel(parent=self.widget)
        self.religion_placeholder.setStyleSheet("border: none;\n"
"font-weight: bold;\n"
"color: rgb(26, 26, 62);\n"
"font-size: 16px")
        self.religion_placeholder.setObjectName("religion_placeholder")
        self.gridLayout.addWidget(self.religion_placeholder, 5, 0, 1, 1)
        self.occupation_placeholder = QtWidgets.QLabel(parent=self.widget)
        self.occupation_placeholder.setStyleSheet("border: none;\n"
"font-weight: bold;\n"
"color: rgb(26, 26, 62);\n"
"font-size: 16px")
        self.occupation_placeholder.setObjectName("occupation_placeholder")
        self.gridLayout.addWidget(self.occupation_placeholder, 5, 1, 1, 1)
        self.contact_number_placeholder = QtWidgets.QLabel(parent=self.widget)
        self.contact_number_placeholder.setStyleSheet("border: none;\n"
"font-weight: bold;\n"
"color: rgb(26, 26, 62);\n"
"font-size: 16px")
        self.contact_number_placeholder.setObjectName("contact_number_placeholder")
        self.gridLayout.addWidget(self.contact_number_placeholder, 5, 2, 1, 1)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_7.setGeometry(QtCore.QRect(40, 540, 461, 161))
        self.frame_7.setStyleSheet("background-color: rgb(236, 198, 220);\n"
"border-radius: 15px;\n"
"border: 1px solid rgb(210, 177, 200);\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.Address_text = QtWidgets.QLabel(parent=self.frame_7)
        self.Address_text.setGeometry(QtCore.QRect(20, 10, 251, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Address_text.sizePolicy().hasHeightForWidth())
        self.Address_text.setSizePolicy(sizePolicy)
        self.Address_text.setStyleSheet("color: rgb(26, 26, 62);\n"
"font-size: 20px;\n"
"border: none;\n"
"font-weight: bold;")
        self.Address_text.setObjectName("Address_text")
        self.widget1 = QtWidgets.QWidget(parent=self.frame_7)
        self.widget1.setGeometry(QtCore.QRect(20, 40, 441, 108))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.street_label = QtWidgets.QLabel(parent=self.widget1)
        self.street_label.setStyleSheet("color: rgb(26, 26, 62);\n"
"border: none;\n"
"font-size: 16px")
        self.street_label.setObjectName("street_label")
        self.gridLayout_2.addWidget(self.street_label, 0, 0, 1, 1)
        self.barangay_label = QtWidgets.QLabel(parent=self.widget1)
        self.barangay_label.setStyleSheet("color: rgb(26, 26, 62);\n"
"border: none;\n"
"font-size: 16px")
        self.barangay_label.setObjectName("barangay_label")
        self.gridLayout_2.addWidget(self.barangay_label, 0, 1, 1, 1)
        self.street_placeholder = QtWidgets.QLabel(parent=self.widget1)
        self.street_placeholder.setStyleSheet("border: none;\n"
"font-weight: bold;\n"
"color:rgb(26, 26, 62);\n"
"font-size: 16px")
        self.street_placeholder.setObjectName("street_placeholder")
        self.gridLayout_2.addWidget(self.street_placeholder, 1, 0, 1, 1)
        self.barangay_placeholder = QtWidgets.QLabel(parent=self.widget1)
        self.barangay_placeholder.setStyleSheet("border: none;\n"
"font-weight: bold;\n"
"color:rgb(26, 26, 62);\n"
"font-size: 16px")
        self.barangay_placeholder.setObjectName("barangay_placeholder")
        self.gridLayout_2.addWidget(self.barangay_placeholder, 1, 1, 1, 1)
        self.city_label = QtWidgets.QLabel(parent=self.widget1)
        self.city_label.setStyleSheet("color: rgb(26, 26, 62);\n"
"font-size: 16px;\n"
"border: none;")
        self.city_label.setObjectName("city_label")
        self.gridLayout_2.addWidget(self.city_label, 2, 0, 1, 1)
        self.province_label = QtWidgets.QLabel(parent=self.widget1)
        self.province_label.setStyleSheet("color: rgb(26, 26, 62);\n"
"font-size: 16px;\n"
"border: none;")
        self.province_label.setObjectName("province_label")
        self.gridLayout_2.addWidget(self.province_label, 2, 1, 1, 1)
        self.cit_placeholder = QtWidgets.QLabel(parent=self.widget1)
        self.cit_placeholder.setStyleSheet("border: none;\n"
"font-weight: bold;\n"
"color: rgb(26, 26, 62);\n"
"font-size: 16px")
        self.cit_placeholder.setObjectName("cit_placeholder")
        self.gridLayout_2.addWidget(self.cit_placeholder, 3, 0, 1, 1)
        self.province_placeholder = QtWidgets.QLabel(parent=self.widget1)
        self.province_placeholder.setStyleSheet("border: none;\n"
"font-weight: bold;\n"
"color: rgb(26, 26, 62);\n"
"font-size: 16px")
        self.province_placeholder.setObjectName("province_placeholder")
        self.gridLayout_2.addWidget(self.province_placeholder, 3, 1, 1, 1)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_8.setGeometry(QtCore.QRect(520, 540, 441, 161))
        self.frame_8.setStyleSheet("background-color: rgb(236, 198, 220);\n"
"border-radius: 15px;\n"
"border: 1px solid rgb(210, 177, 200);\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.Emergency_text = QtWidgets.QLabel(parent=self.frame_8)
        self.Emergency_text.setGeometry(QtCore.QRect(20, 10, 251, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Emergency_text.sizePolicy().hasHeightForWidth())
        self.Emergency_text.setSizePolicy(sizePolicy)
        self.Emergency_text.setStyleSheet("color: rgb(26, 26, 62);\n"
"font-size: 20px;\n"
"border: none;\n"
"font-weight: bold;")
        self.Emergency_text.setObjectName("Emergency_text")
        self.widget2 = QtWidgets.QWidget(parent=self.frame_8)
        self.widget2.setGeometry(QtCore.QRect(20, 40, 421, 108))
        self.widget2.setObjectName("widget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.EC_last_name_label = QtWidgets.QLabel(parent=self.widget2)
        self.EC_last_name_label.setStyleSheet("color: rgb(26, 26, 62);\n"
"border: none;\n"
"font-size: 16px")
        self.EC_last_name_label.setObjectName("EC_last_name_label")
        self.gridLayout_3.addWidget(self.EC_last_name_label, 0, 0, 1, 1)
        self.EC_first_name_label = QtWidgets.QLabel(parent=self.widget2)
        self.EC_first_name_label.setStyleSheet("color: rgb(26, 26, 62);\n"
"border: none;\n"
"font-size: 16px")
        self.EC_first_name_label.setObjectName("EC_first_name_label")
        self.gridLayout_3.addWidget(self.EC_first_name_label, 0, 1, 1, 1)
        self.EC_middle_name_label = QtWidgets.QLabel(parent=self.widget2)
        self.EC_middle_name_label.setStyleSheet("color: rgb(26, 26, 62);\n"
"border: none;\n"
"font-size: 16px")
        self.EC_middle_name_label.setObjectName("EC_middle_name_label")
        self.gridLayout_3.addWidget(self.EC_middle_name_label, 0, 2, 1, 1)
        self.EC_last_name_placeholder = QtWidgets.QLabel(parent=self.widget2)
        self.EC_last_name_placeholder.setStyleSheet("border: none;\n"
"font-weight: bold;\n"
"color:rgb(26, 26, 62);\n"
"font-size: 16px")
        self.EC_last_name_placeholder.setObjectName("EC_last_name_placeholder")
        self.gridLayout_3.addWidget(self.EC_last_name_placeholder, 1, 0, 1, 1)
        self.EC_first_name_placeholder = QtWidgets.QLabel(parent=self.widget2)
        self.EC_first_name_placeholder.setStyleSheet("border: none;\n"
"font-weight: bold;\n"
"color:rgb(26, 26, 62);\n"
"font-size: 16px")
        self.EC_first_name_placeholder.setObjectName("EC_first_name_placeholder")
        self.gridLayout_3.addWidget(self.EC_first_name_placeholder, 1, 1, 1, 1)
        self.EC_middle_name_placeholder = QtWidgets.QLabel(parent=self.widget2)
        self.EC_middle_name_placeholder.setStyleSheet("border: none;\n"
"font-weight: bold;\n"
"color:rgb(26, 26, 62);\n"
"font-size: 16px")
        self.EC_middle_name_placeholder.setObjectName("EC_middle_name_placeholder")
        self.gridLayout_3.addWidget(self.EC_middle_name_placeholder, 1, 2, 1, 1)
        self.EC_contact_label = QtWidgets.QLabel(parent=self.widget2)
        self.EC_contact_label.setStyleSheet("color: rgb(26, 26, 62);\n"
"border: none;\n"
"font-size: 16px")
        self.EC_contact_label.setObjectName("EC_contact_label")
        self.gridLayout_3.addWidget(self.EC_contact_label, 2, 0, 1, 1)
        self.EC_relationship_label = QtWidgets.QLabel(parent=self.widget2)
        self.EC_relationship_label.setStyleSheet("color: rgb(26, 26, 62);\n"
"border: none;\n"
"font-size: 16px")
        self.EC_relationship_label.setObjectName("EC_relationship_label")
        self.gridLayout_3.addWidget(self.EC_relationship_label, 2, 1, 1, 1)
        self.EC_contact_placeholder = QtWidgets.QLabel(parent=self.widget2)
        self.EC_contact_placeholder.setStyleSheet("border: none;\n"
"font-weight: bold;\n"
"color:rgb(26, 26, 62);\n"
"font-size: 16px")
        self.EC_contact_placeholder.setObjectName("EC_contact_placeholder")
        self.gridLayout_3.addWidget(self.EC_contact_placeholder, 3, 0, 1, 1)
        self.EC_relationship_placeholder = QtWidgets.QLabel(parent=self.widget2)
        self.EC_relationship_placeholder.setStyleSheet("border: none;\n"
"font-weight: bold;\n"
"color:rgb(26, 26, 62);\n"
"font-size: 16px")
        self.EC_relationship_placeholder.setObjectName("EC_relationship_placeholder")
        self.gridLayout_3.addWidget(self.EC_relationship_placeholder, 3, 1, 1, 2)
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame_3)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 240, 798, 40))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54; /* underline */\n"
"}\n"
"\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54; /* underline */\n"
"}\n"
"\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54; /* underline */\n"
"}\n"
"\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54; /* underline */\n"
"}\n"
"\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54; /* underline */\n"
"}\n"
"\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54; /* underline */\n"
"}\n"
"\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout.addWidget(self.pushButton_11)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1230, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_2.setText(_translate("MainWindow", "Patient Records"))
        self.pushButton_3.setText(_translate("MainWindow", "Prenatal Care"))
        self.pushButton_4.setText(_translate("MainWindow", "       Appointments        "))
        self.pushButton_5.setText(_translate("MainWindow", "Log out"))
        self.label_2.setText(_translate("MainWindow", "MATERNADB"))
        self.label_3.setText(_translate("MainWindow", "LOGO"))
        self.label.setText(_translate("MainWindow", "Patient Records"))
        self.remove_patient_btn.setText(_translate("MainWindow", "Edit Patient Profile"))
        self.patient_name.setText(_translate("MainWindow", "NAME"))
        self.patient_id_label.setText(_translate("MainWindow", "Patient ID:"))
        self.patient_id_label_2.setText(_translate("MainWindow", "Blood Type:"))
        self.placeholder_p_ID.setText(_translate("MainWindow", "placeholder"))
        self.placeholder_p_bloodType.setText(_translate("MainWindow", "placeholder"))
        self.placeholder_register_date.setText(_translate("MainWindow", "MM/DD/YYYY"))
        self.patient_id_label_3.setText(_translate("MainWindow", "Registered:"))
        self.placeholder_philhealth_num.setText(_translate("MainWindow", "1234-5676-8907"))
        self.patient_id_label_4.setText(_translate("MainWindow", "PhilHealth#:"))
        self.next_btn.setText(_translate("MainWindow", "Next"))
        self.personalInformation_text.setText(_translate("MainWindow", "PERSONAL INFORMATION"))
        self.last_name_placeholder_2.setText(_translate("MainWindow", "LAST NAME"))
        self.first_name_label.setText(_translate("MainWindow", "FIRST NAME"))
        self.middle_name_label.setText(_translate("MainWindow", "MIDDLE NAME"))
        self.last_name_placeholder.setText(_translate("MainWindow", "placeholder"))
        self.first_name_placeholder.setText(_translate("MainWindow", "placeholder"))
        self.middle_name_placeholder.setText(_translate("MainWindow", "placeholder"))
        self.date_of_birth_placeholder.setText(_translate("MainWindow", "DATE OF BIRTH"))
        self.civi_status_label.setText(_translate("MainWindow", "CIVIL STATUS"))
        self.nationality_label.setText(_translate("MainWindow", "NATIONALITY"))
        self.bday_placeholder.setText(_translate("MainWindow", "MM/DD/YYYY"))
        self.civil_status_placeholder.setText(_translate("MainWindow", "placeholder"))
        self.nationality_placeholder.setText(_translate("MainWindow", "placeholder"))
        self.religion_placeholder_2.setText(_translate("MainWindow", "RELIGION"))
        self.occupation_label.setText(_translate("MainWindow", "OCCUPATION"))
        self.contact_number_label.setText(_translate("MainWindow", "CONTACT#"))
        self.religion_placeholder.setText(_translate("MainWindow", "placeholder"))
        self.occupation_placeholder.setText(_translate("MainWindow", "placeholder"))
        self.contact_number_placeholder.setText(_translate("MainWindow", "placeholder"))
        self.Address_text.setText(_translate("MainWindow", "ADDRESS"))
        self.street_label.setText(_translate("MainWindow", "STREET"))
        self.barangay_label.setText(_translate("MainWindow", "BARANGAY"))
        self.street_placeholder.setText(_translate("MainWindow", "placeholder"))
        self.barangay_placeholder.setText(_translate("MainWindow", "placeholder"))
        self.city_label.setText(_translate("MainWindow", "CITY"))
        self.province_label.setText(_translate("MainWindow", "PROVINCE"))
        self.cit_placeholder.setText(_translate("MainWindow", "placeholder"))
        self.province_placeholder.setText(_translate("MainWindow", "placeholder"))
        self.Emergency_text.setText(_translate("MainWindow", "Emergency Contact"))
        self.EC_last_name_label.setText(_translate("MainWindow", "LAST NAME"))
        self.EC_first_name_label.setText(_translate("MainWindow", "FIRST NAME"))
        self.EC_middle_name_label.setText(_translate("MainWindow", "MIDDLE NAME"))
        self.EC_last_name_placeholder.setText(_translate("MainWindow", "placeholder"))
        self.EC_first_name_placeholder.setText(_translate("MainWindow", "placeholder"))
        self.EC_middle_name_placeholder.setText(_translate("MainWindow", "placeholder"))
        self.EC_contact_label.setText(_translate("MainWindow", "CONTACT#"))
        self.EC_relationship_label.setText(_translate("MainWindow", "RELATIONSHIP"))
        self.EC_contact_placeholder.setText(_translate("MainWindow", "placeholder"))
        self.EC_relationship_placeholder.setText(_translate("MainWindow", "placeholder"))
        self.pushButton_6.setText(_translate("MainWindow", "Patient Profile"))
        self.pushButton_7.setText(_translate("MainWindow", "Past Pregnancy"))
        self.pushButton_8.setText(_translate("MainWindow", "Prescriptions"))
        self.pushButton_9.setText(_translate("MainWindow", "Medical History"))
        self.pushButton_10.setText(_translate("MainWindow", "Family Planning"))
        self.pushButton_11.setText(_translate("MainWindow", "Appointments"))
