# Form implementation generated from reading ui file 'Ui/patient_profile_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PatientProfileDialog(object):
    def setupUi(self, StackedWidget):
        StackedWidget.setObjectName("StackedWidget")
        StackedWidget.resize(400, 533)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame = QtWidgets.QFrame(parent=self.page)
        self.frame.setGeometry(QtCore.QRect(0, 0, 401, 531))
        self.frame.setStyleSheet("background-color: rgb(240, 230, 240);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.personalInformation_label = QtWidgets.QLabel(parent=self.frame)
        self.personalInformation_label.setGeometry(QtCore.QRect(80, 10, 241, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.personalInformation_label.sizePolicy().hasHeightForWidth())
        self.personalInformation_label.setSizePolicy(sizePolicy)
        self.personalInformation_label.setStyleSheet("font: 16pt \"Segoe UI\";")
        self.personalInformation_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.personalInformation_label.setObjectName("personalInformation_label")
        self.firstName = QtWidgets.QLabel(parent=self.frame)
        self.firstName.setGeometry(QtCore.QRect(40, 70, 91, 16))
        self.firstName.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.firstName.setObjectName("firstName")
        self.lastName = QtWidgets.QLabel(parent=self.frame)
        self.lastName.setGeometry(QtCore.QRect(200, 70, 91, 16))
        self.lastName.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.lastName.setObjectName("lastName")
        self.suffix = QtWidgets.QLabel(parent=self.frame)
        self.suffix.setGeometry(QtCore.QRect(200, 130, 91, 16))
        self.suffix.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.suffix.setObjectName("suffix")
        self.middleName = QtWidgets.QLabel(parent=self.frame)
        self.middleName.setGeometry(QtCore.QRect(40, 130, 141, 16))
        self.middleName.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.middleName.setObjectName("middleName")
        self.dateOfBirth = QtWidgets.QLabel(parent=self.frame)
        self.dateOfBirth.setGeometry(QtCore.QRect(40, 190, 91, 16))
        self.dateOfBirth.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.dateOfBirth.setObjectName("dateOfBirth")
        self.dateOfBirth_placeholder = QtWidgets.QDateEdit(parent=self.frame)
        self.dateOfBirth_placeholder.setGeometry(QtCore.QRect(40, 210, 151, 31))
        self.dateOfBirth_placeholder.setStyleSheet("QDateEdit {\n"
"    border: 1px solid #6c6c8a;\n"
"    border-radius: 10px;\n"
"    padding: 6px 10px;\n"
"    padding-right: 30px; /* space for icon */\n"
"    background: transparent;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    border: none;\n"
"    width: 20px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow {\n"
"    image: url(:/icons/calendar.png); /* optional custom icon */\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}")
        self.dateOfBirth_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dateOfBirth_placeholder.setCalendarPopup(True)
        self.dateOfBirth_placeholder.setObjectName("dateOfBirth_placeholder")
        self.firstName_placeholder = QtWidgets.QLineEdit(parent=self.frame)
        self.firstName_placeholder.setGeometry(QtCore.QRect(40, 90, 151, 31))
        self.firstName_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.firstName_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.firstName_placeholder.setObjectName("firstName_placeholder")
        self.suffix_placeholder = QtWidgets.QLineEdit(parent=self.frame)
        self.suffix_placeholder.setGeometry(QtCore.QRect(200, 150, 151, 31))
        self.suffix_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.suffix_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.suffix_placeholder.setObjectName("suffix_placeholder")
        self.lastName_placeholder = QtWidgets.QLineEdit(parent=self.frame)
        self.lastName_placeholder.setGeometry(QtCore.QRect(200, 90, 151, 31))
        self.lastName_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.lastName_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lastName_placeholder.setObjectName("lastName_placeholder")
        self.middleName_placeholder = QtWidgets.QLineEdit(parent=self.frame)
        self.middleName_placeholder.setGeometry(QtCore.QRect(40, 150, 151, 31))
        self.middleName_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.middleName_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.middleName_placeholder.setObjectName("middleName_placeholder")
        self.civilStatus_placeholder = QtWidgets.QLineEdit(parent=self.frame)
        self.civilStatus_placeholder.setGeometry(QtCore.QRect(200, 210, 151, 31))
        self.civilStatus_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.civilStatus_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.civilStatus_placeholder.setObjectName("civilStatus_placeholder")
        self.civilStatus = QtWidgets.QLabel(parent=self.frame)
        self.civilStatus.setGeometry(QtCore.QRect(200, 190, 91, 16))
        self.civilStatus.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.civilStatus.setObjectName("civilStatus")
        self.contactNum_placeholder = QtWidgets.QLineEdit(parent=self.frame)
        self.contactNum_placeholder.setGeometry(QtCore.QRect(40, 270, 151, 31))
        self.contactNum_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.contactNum_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.contactNum_placeholder.setObjectName("contactNum_placeholder")
        self.contactNum = QtWidgets.QLabel(parent=self.frame)
        self.contactNum.setGeometry(QtCore.QRect(40, 250, 101, 16))
        self.contactNum.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.contactNum.setObjectName("contactNum")
        self.philHealth_placeholder = QtWidgets.QLineEdit(parent=self.frame)
        self.philHealth_placeholder.setGeometry(QtCore.QRect(40, 330, 151, 31))
        self.philHealth_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.philHealth_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.philHealth_placeholder.setObjectName("philHealth_placeholder")
        self.philHealth = QtWidgets.QLabel(parent=self.frame)
        self.philHealth.setGeometry(QtCore.QRect(40, 310, 91, 16))
        self.philHealth.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.philHealth.setObjectName("philHealth")
        self.occupation = QtWidgets.QLabel(parent=self.frame)
        self.occupation.setGeometry(QtCore.QRect(200, 250, 141, 16))
        self.occupation.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.occupation.setObjectName("occupation")
        self.occupation_placeholder = QtWidgets.QLineEdit(parent=self.frame)
        self.occupation_placeholder.setGeometry(QtCore.QRect(200, 270, 151, 31))
        self.occupation_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.occupation_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.occupation_placeholder.setObjectName("occupation_placeholder")
        self.Religion = QtWidgets.QLabel(parent=self.frame)
        self.Religion.setGeometry(QtCore.QRect(40, 370, 91, 21))
        self.Religion.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.Religion.setObjectName("Religion")
        self.religion_placeholder = QtWidgets.QLineEdit(parent=self.frame)
        self.religion_placeholder.setGeometry(QtCore.QRect(40, 390, 151, 31))
        self.religion_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.religion_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.religion_placeholder.setObjectName("religion_placeholder")
        self.nationality = QtWidgets.QLabel(parent=self.frame)
        self.nationality.setGeometry(QtCore.QRect(200, 310, 91, 16))
        self.nationality.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.nationality.setObjectName("nationality")
        self.nationality_placeholder = QtWidgets.QLineEdit(parent=self.frame)
        self.nationality_placeholder.setGeometry(QtCore.QRect(200, 330, 151, 31))
        self.nationality_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.nationality_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.nationality_placeholder.setObjectName("nationality_placeholder")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 450, 320, 28))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton.setStyleSheet("border-radius: 12px;\n"
"padding: 4px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_2.setStyleSheet("border-radius: 12px;\n"
"padding: 4px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_3.setStyleSheet("border-radius: 12px;\n"
"padding: 4px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.Religion_2 = QtWidgets.QLabel(parent=self.frame)
        self.Religion_2.setGeometry(QtCore.QRect(200, 370, 91, 21))
        self.Religion_2.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.Religion_2.setObjectName("Religion_2")
        self.religion_placeholder_2 = QtWidgets.QLineEdit(parent=self.frame)
        self.religion_placeholder_2.setGeometry(QtCore.QRect(200, 390, 151, 31))
        self.religion_placeholder_2.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.religion_placeholder_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.religion_placeholder_2.setObjectName("religion_placeholder_2")
        StackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 401, 531))
        self.frame_2.setStyleSheet("background-color: rgb(240, 230, 240);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.address_label = QtWidgets.QLabel(parent=self.frame_2)
        self.address_label.setGeometry(QtCore.QRect(80, 10, 241, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.address_label.sizePolicy().hasHeightForWidth())
        self.address_label.setSizePolicy(sizePolicy)
        self.address_label.setStyleSheet("font: 16pt \"Segoe UI\";")
        self.address_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.address_label.setObjectName("address_label")
        self.street_label = QtWidgets.QLabel(parent=self.frame_2)
        self.street_label.setGeometry(QtCore.QRect(40, 60, 91, 16))
        self.street_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.street_label.setObjectName("street_label")
        self.barangay_label = QtWidgets.QLabel(parent=self.frame_2)
        self.barangay_label.setGeometry(QtCore.QRect(200, 60, 91, 16))
        self.barangay_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.barangay_label.setObjectName("barangay_label")
        self.province_label = QtWidgets.QLabel(parent=self.frame_2)
        self.province_label.setGeometry(QtCore.QRect(200, 120, 91, 16))
        self.province_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.province_label.setObjectName("province_label")
        self.city_label = QtWidgets.QLabel(parent=self.frame_2)
        self.city_label.setGeometry(QtCore.QRect(40, 120, 141, 16))
        self.city_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.city_label.setObjectName("city_label")
        self.street_placeholder = QtWidgets.QLineEdit(parent=self.frame_2)
        self.street_placeholder.setGeometry(QtCore.QRect(40, 80, 151, 31))
        self.street_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.street_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.street_placeholder.setObjectName("street_placeholder")
        self.province_placeholder = QtWidgets.QLineEdit(parent=self.frame_2)
        self.province_placeholder.setGeometry(QtCore.QRect(200, 140, 151, 31))
        self.province_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.province_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.province_placeholder.setObjectName("province_placeholder")
        self.barangay_placeholder = QtWidgets.QLineEdit(parent=self.frame_2)
        self.barangay_placeholder.setGeometry(QtCore.QRect(200, 80, 151, 31))
        self.barangay_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.barangay_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.barangay_placeholder.setObjectName("barangay_placeholder")
        self.city_placeholder = QtWidgets.QLineEdit(parent=self.frame_2)
        self.city_placeholder.setGeometry(QtCore.QRect(40, 140, 151, 31))
        self.city_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.city_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.city_placeholder.setObjectName("city_placeholder")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.frame_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 450, 320, 28))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.back_btn_2 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.back_btn_2.setStyleSheet("border-radius: 12px;\n"
"padding: 4px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.back_btn_2.setObjectName("back_btn_2")
        self.horizontalLayout_2.addWidget(self.back_btn_2)
        self.cancel_btn_2 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.cancel_btn_2.setStyleSheet("border-radius: 12px;\n"
"padding: 4px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.cancel_btn_2.setObjectName("cancel_btn_2")
        self.horizontalLayout_2.addWidget(self.cancel_btn_2)
        self.save_btn_2 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.save_btn_2.setStyleSheet("border-radius: 12px;\n"
"padding: 4px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.save_btn_2.setObjectName("save_btn_2")
        self.horizontalLayout_2.addWidget(self.save_btn_2)
        self.emergencyContact_label = QtWidgets.QLabel(parent=self.frame_2)
        self.emergencyContact_label.setGeometry(QtCore.QRect(80, 190, 241, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emergencyContact_label.sizePolicy().hasHeightForWidth())
        self.emergencyContact_label.setSizePolicy(sizePolicy)
        self.emergencyContact_label.setStyleSheet("font: 16pt \"Segoe UI\";")
        self.emergencyContact_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.emergencyContact_label.setObjectName("emergencyContact_label")
        self.dateOfBirth_4 = QtWidgets.QLabel(parent=self.frame_2)
        self.dateOfBirth_4.setGeometry(QtCore.QRect(200, 300, 91, 16))
        self.dateOfBirth_4.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.dateOfBirth_4.setObjectName("dateOfBirth_4")
        self.relationship_placeholder_2 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.relationship_placeholder_2.setGeometry(QtCore.QRect(40, 380, 151, 31))
        self.relationship_placeholder_2.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.relationship_placeholder_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.relationship_placeholder_2.setObjectName("relationship_placeholder_2")
        self.EC_last_name_placeholder_2 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.EC_last_name_placeholder_2.setGeometry(QtCore.QRect(200, 260, 151, 31))
        self.EC_last_name_placeholder_2.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.EC_last_name_placeholder_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.EC_last_name_placeholder_2.setObjectName("EC_last_name_placeholder_2")
        self.EC_firstName_placeholder_2 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.EC_firstName_placeholder_2.setGeometry(QtCore.QRect(40, 260, 151, 31))
        self.EC_firstName_placeholder_2.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.EC_firstName_placeholder_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.EC_firstName_placeholder_2.setObjectName("EC_firstName_placeholder_2")
        self.EC_firstName_label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.EC_firstName_label_2.setGeometry(QtCore.QRect(40, 240, 91, 16))
        self.EC_firstName_label_2.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.EC_firstName_label_2.setObjectName("EC_firstName_label_2")
        self.EC_middleName_label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.EC_middleName_label_2.setGeometry(QtCore.QRect(40, 300, 141, 16))
        self.EC_middleName_label_2.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.EC_middleName_label_2.setObjectName("EC_middleName_label_2")
        self.relationship_label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.relationship_label_2.setGeometry(QtCore.QRect(40, 360, 91, 16))
        self.relationship_label_2.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.relationship_label_2.setObjectName("relationship_label_2")
        self.EC_middleName_placeholder_2 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.EC_middleName_placeholder_2.setGeometry(QtCore.QRect(40, 320, 151, 31))
        self.EC_middleName_placeholder_2.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.EC_middleName_placeholder_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.EC_middleName_placeholder_2.setObjectName("EC_middleName_placeholder_2")
        self.emergencyNum_placeholder_2 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.emergencyNum_placeholder_2.setGeometry(QtCore.QRect(200, 320, 151, 31))
        self.emergencyNum_placeholder_2.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.emergencyNum_placeholder_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.emergencyNum_placeholder_2.setObjectName("emergencyNum_placeholder_2")
        self.EC_lastName_label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.EC_lastName_label_2.setGeometry(QtCore.QRect(200, 240, 101, 16))
        self.EC_lastName_label_2.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.EC_lastName_label_2.setObjectName("EC_lastName_label_2")
        StackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.frame_3 = QtWidgets.QFrame(parent=self.page_3)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 401, 331))
        self.frame_3.setStyleSheet("background-color: rgb(240, 230, 240);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(80, 10, 241, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("font: 16pt \"Segoe UI\";")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.dateOfBirth_3 = QtWidgets.QLabel(parent=self.frame_3)
        self.dateOfBirth_3.setGeometry(QtCore.QRect(200, 110, 91, 31))
        self.dateOfBirth_3.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.dateOfBirth_3.setObjectName("dateOfBirth_3")
        self.EC_firstName_placeholder = QtWidgets.QLineEdit(parent=self.frame_3)
        self.EC_firstName_placeholder.setGeometry(QtCore.QRect(40, 80, 151, 31))
        self.EC_firstName_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.EC_firstName_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.EC_firstName_placeholder.setObjectName("EC_firstName_placeholder")
        self.EC_firstName_label = QtWidgets.QLabel(parent=self.frame_3)
        self.EC_firstName_label.setGeometry(QtCore.QRect(40, 60, 91, 16))
        self.EC_firstName_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.EC_firstName_label.setObjectName("EC_firstName_label")
        self.EC_last_name_placeholder = QtWidgets.QLineEdit(parent=self.frame_3)
        self.EC_last_name_placeholder.setGeometry(QtCore.QRect(200, 80, 151, 31))
        self.EC_last_name_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.EC_last_name_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.EC_last_name_placeholder.setObjectName("EC_last_name_placeholder")
        self.EC_lastName_label = QtWidgets.QLabel(parent=self.frame_3)
        self.EC_lastName_label.setGeometry(QtCore.QRect(200, 60, 101, 16))
        self.EC_lastName_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.EC_lastName_label.setObjectName("EC_lastName_label")
        self.relationship_placeholder = QtWidgets.QLineEdit(parent=self.frame_3)
        self.relationship_placeholder.setGeometry(QtCore.QRect(40, 200, 151, 31))
        self.relationship_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.relationship_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.relationship_placeholder.setObjectName("relationship_placeholder")
        self.relationship_label = QtWidgets.QLabel(parent=self.frame_3)
        self.relationship_label.setGeometry(QtCore.QRect(40, 180, 91, 16))
        self.relationship_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.relationship_label.setObjectName("relationship_label")
        self.EC_middleName_label = QtWidgets.QLabel(parent=self.frame_3)
        self.EC_middleName_label.setGeometry(QtCore.QRect(40, 120, 141, 16))
        self.EC_middleName_label.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.EC_middleName_label.setObjectName("EC_middleName_label")
        self.EC_middleName_placeholder = QtWidgets.QLineEdit(parent=self.frame_3)
        self.EC_middleName_placeholder.setGeometry(QtCore.QRect(40, 140, 151, 31))
        self.EC_middleName_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.EC_middleName_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.EC_middleName_placeholder.setObjectName("EC_middleName_placeholder")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.frame_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(40, 260, 320, 28))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.back_btn = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.back_btn.setStyleSheet("border-radius: 12px;\n"
"padding: 4px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout_3.addWidget(self.back_btn)
        self.cancel_btn = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.cancel_btn.setStyleSheet("border-radius: 12px;\n"
"padding: 4px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_3.addWidget(self.cancel_btn)
        self.save_btn = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.save_btn.setStyleSheet("border-radius: 12px;\n"
"padding: 4px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_3.addWidget(self.save_btn)
        self.emergencyNum_placeholder = QtWidgets.QLineEdit(parent=self.frame_3)
        self.emergencyNum_placeholder.setGeometry(QtCore.QRect(200, 140, 151, 31))
        self.emergencyNum_placeholder.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(240, 230, 240);\n"
"border: 1px solid rgb(26, 26, 62);")
        self.emergencyNum_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.emergencyNum_placeholder.setObjectName("emergencyNum_placeholder")
        StackedWidget.addWidget(self.page_3)

        self.retranslateUi(StackedWidget)
        StackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(StackedWidget)

    def retranslateUi(self, StackedWidget):
        _translate = QtCore.QCoreApplication.translate
        StackedWidget.setWindowTitle(_translate("StackedWidget", "StackedWidget"))
        self.personalInformation_label.setText(_translate("StackedWidget", "Personal Information"))
        self.firstName.setText(_translate("StackedWidget", "First Name"))
        self.lastName.setText(_translate("StackedWidget", "Last Name"))
        self.suffix.setText(_translate("StackedWidget", "Suffix (Optional)"))
        self.middleName.setText(_translate("StackedWidget", "Middle Name (Optional)"))
        self.dateOfBirth.setText(_translate("StackedWidget", "Date of Birth"))
        self.firstName_placeholder.setText(_translate("StackedWidget", "e.g., Juan"))
        self.suffix_placeholder.setText(_translate("StackedWidget", "e.g. Jr.,"))
        self.lastName_placeholder.setText(_translate("StackedWidget", "e.g., Dela Cruz"))
        self.middleName_placeholder.setText(_translate("StackedWidget", "e.g., Ocampo"))
        self.civilStatus_placeholder.setText(_translate("StackedWidget", "e.g,. Married"))
        self.civilStatus.setText(_translate("StackedWidget", "Civil Status"))
        self.contactNum_placeholder.setText(_translate("StackedWidget", "e.g., 091234567890"))
        self.contactNum.setText(_translate("StackedWidget", "Contact Number"))
        self.philHealth_placeholder.setText(_translate("StackedWidget", "e.g., 12-345678901-2"))
        self.philHealth.setText(_translate("StackedWidget", "PhilHealth#"))
        self.occupation.setText(_translate("StackedWidget", "Occupation (Optional)"))
        self.occupation_placeholder.setText(_translate("StackedWidget", "e.g., Housewife"))
        self.Religion.setText(_translate("StackedWidget", "Religion"))
        self.religion_placeholder.setText(_translate("StackedWidget", "e.g., Roman Catholic"))
        self.nationality.setText(_translate("StackedWidget", "Nationaliy"))
        self.nationality_placeholder.setText(_translate("StackedWidget", "e.g., Filipino"))
        self.pushButton.setText(_translate("StackedWidget", "Cancel"))
        self.pushButton_2.setText(_translate("StackedWidget", "Save"))
        self.pushButton_3.setText(_translate("StackedWidget", "Next"))
        self.Religion_2.setText(_translate("StackedWidget", "Blood Type"))
        self.religion_placeholder_2.setText(_translate("StackedWidget", "e.g., -O"))
        self.address_label.setText(_translate("StackedWidget", "Address"))
        self.street_label.setText(_translate("StackedWidget", "Street"))
        self.barangay_label.setText(_translate("StackedWidget", "Barangay"))
        self.province_label.setText(_translate("StackedWidget", "Province"))
        self.city_label.setText(_translate("StackedWidget", "City"))
        self.street_placeholder.setText(_translate("StackedWidget", "e.g., Juan"))
        self.province_placeholder.setText(_translate("StackedWidget", "e.g. Jr.,"))
        self.barangay_placeholder.setText(_translate("StackedWidget", "e.g., Dela Cruz"))
        self.city_placeholder.setText(_translate("StackedWidget", "e.g., Ocampo"))
        self.back_btn_2.setText(_translate("StackedWidget", "Back"))
        self.cancel_btn_2.setText(_translate("StackedWidget", "Cancel"))
        self.save_btn_2.setText(_translate("StackedWidget", "Save"))
        self.emergencyContact_label.setText(_translate("StackedWidget", "Emergency Contact"))
        self.dateOfBirth_4.setText(_translate("StackedWidget", "Emergency #"))
        self.relationship_placeholder_2.setText(_translate("StackedWidget", "e.g., Husband"))
        self.EC_last_name_placeholder_2.setText(_translate("StackedWidget", "e.g., Dela Cruz"))
        self.EC_firstName_placeholder_2.setText(_translate("StackedWidget", "e.g,. Maria"))
        self.EC_firstName_label_2.setText(_translate("StackedWidget", "First Name"))
        self.EC_middleName_label_2.setText(_translate("StackedWidget", "Middle Name"))
        self.relationship_label_2.setText(_translate("StackedWidget", "Relationship"))
        self.EC_middleName_placeholder_2.setText(_translate("StackedWidget", "e.g., Ocampo"))
        self.emergencyNum_placeholder_2.setText(_translate("StackedWidget", "e.g., 091234567890"))
        self.EC_lastName_label_2.setText(_translate("StackedWidget", "Last Name"))
        self.label_3.setText(_translate("StackedWidget", "Emergency Contact"))
        self.dateOfBirth_3.setText(_translate("StackedWidget", "Emergency #"))
        self.EC_firstName_placeholder.setText(_translate("StackedWidget", "e.g,. Maria"))
        self.EC_firstName_label.setText(_translate("StackedWidget", "First Name"))
        self.EC_last_name_placeholder.setText(_translate("StackedWidget", "e.g., Dela Cruz"))
        self.EC_lastName_label.setText(_translate("StackedWidget", "Last Name"))
        self.relationship_placeholder.setText(_translate("StackedWidget", "e.g., Husband"))
        self.relationship_label.setText(_translate("StackedWidget", "Relationship"))
        self.EC_middleName_label.setText(_translate("StackedWidget", "Middle Name"))
        self.EC_middleName_placeholder.setText(_translate("StackedWidget", "e.g., Ocampo"))
        self.back_btn.setText(_translate("StackedWidget", "Back"))
        self.cancel_btn.setText(_translate("StackedWidget", "Cancel"))
        self.save_btn.setText(_translate("StackedWidget", "Save"))
        self.emergencyNum_placeholder.setText(_translate("StackedWidget", "e.g., 091234567890"))
