# Form implementation generated from reading ui file 'Ui/patient_records_.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PatientRecord(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1230, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 60, 231, 611))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet(" background-color: rgb(192, 116, 182)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 180, 191, 41))
        self.pushButton.setStyleSheet("background-color: rgb(240, 230, 240)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 230, 221, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(240, 230, 240)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 280, 191, 41))
        self.pushButton_3.setStyleSheet("background-color: rgb(240, 230, 240)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 330, 191, 41))
        self.pushButton_4.setStyleSheet("background-color: rgb(240, 230, 240)")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 500, 191, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1231, 61))
        self.frame_2.setStyleSheet("background-color: rgb(26, 26, 62)\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(130, 10, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 100, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(230, 60, 1001, 601))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("background-color: rgb(240, 230, 240)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setGeometry(QtCore.QRect(40, 20, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.patient_table = QtWidgets.QTableWidget(parent=self.frame_3)
        self.patient_table.setGeometry(QtCore.QRect(40, 140, 941, 371))
        self.patient_table.setAutoFillBackground(True)
        self.patient_table.setStyleSheet("QTableWidget {\n"
"    background-color:rgb(236, 198, 220);\n"
"    border: 1px solid rgb(158, 136, 163);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    background-color: rgb(236, 198, 220);\n"
"    color: rgb(21, 23, 61);\n"
"    padding: 8px;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(210, 177, 200);\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    color: rgb(21, 23, 61);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(236, 198, 220);\n"
"    color: rgb(21, 23, 61);\n"
"    font-weight: bold;\n"
"    font-size: 10px;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(155, 132, 160);\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: white;\n"
"    width: 6px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(178, 100, 168);\n"
"    border-radius: 3px;\n"
"}")
        self.patient_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.patient_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.patient_table.setAlternatingRowColors(False)
        self.patient_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.patient_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.patient_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.patient_table.setShowGrid(False)
        self.patient_table.setObjectName("patient_table")
        self.patient_table.setColumnCount(5)
        self.patient_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setHorizontalHeaderItem(4, item)
        self.patient_table.horizontalHeader().setCascadingSectionResizes(False)
        self.patient_table.horizontalHeader().setDefaultSectionSize(150)
        self.patient_table.horizontalHeader().setHighlightSections(True)
        self.patient_table.horizontalHeader().setMinimumSectionSize(32)
        self.patient_table.horizontalHeader().setSortIndicatorShown(False)
        self.patient_table.horizontalHeader().setStretchLastSection(True)
        self.patient_table.verticalHeader().setVisible(False)
        self.patient_table.verticalHeader().setCascadingSectionResizes(False)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_3)
        self.lineEdit.setGeometry(QtCore.QRect(40, 90, 291, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setStyleSheet("background-color: rgb(224, 188, 209);\n"
"border-radius: 15px;\n"
"border: 1px solid rgb(177, 152, 177);")
        self.lineEdit.setObjectName("lineEdit")
        self.add_patient_btn = QtWidgets.QPushButton(parent=self.frame_3)
        self.add_patient_btn.setGeometry(QtCore.QRect(730, 100, 121, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_patient_btn.sizePolicy().hasHeightForWidth())
        self.add_patient_btn.setSizePolicy(sizePolicy)
        self.add_patient_btn.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(236, 198, 220);\n"
"border: 1px solid rgb(210, 177, 200);")
        self.add_patient_btn.setObjectName("add_patient_btn")
        self.remove_patient_btn = QtWidgets.QPushButton(parent=self.frame_3)
        self.remove_patient_btn.setGeometry(QtCore.QRect(860, 100, 121, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_patient_btn.sizePolicy().hasHeightForWidth())
        self.remove_patient_btn.setSizePolicy(sizePolicy)
        self.remove_patient_btn.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(236, 198, 220);\n"
"border: 1px solid rgb(210, 177, 200);")
        self.remove_patient_btn.setObjectName("remove_patient_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1230, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_2.setText(_translate("MainWindow", "Patient Records"))
        self.pushButton_3.setText(_translate("MainWindow", "Prenatal Care"))
        self.pushButton_4.setText(_translate("MainWindow", "Appointments        "))
        self.pushButton_5.setText(_translate("MainWindow", "Log out"))
        self.label_2.setText(_translate("MainWindow", "MATERNADB"))
        self.label_3.setText(_translate("MainWindow", "LOGO"))
        self.label.setText(_translate("MainWindow", "Patient Records"))
        item = self.patient_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "#0001"))
        item = self.patient_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PATIENT#"))
        item = self.patient_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NAME"))
        item = self.patient_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DATE OF BIRTH"))
        item = self.patient_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "CONTACT"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "           Search for patient"))
        self.add_patient_btn.setText(_translate("MainWindow", "Add Patient"))
        self.remove_patient_btn.setText(_translate("MainWindow", "Remove Patient"))
