# Form implementation generated from reading ui file 'Ui/prescription.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1301, 864)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 60, 231, 761))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet(" background-color: rgb(192, 116, 182)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 180, 191, 41))
        self.pushButton.setStyleSheet("background-color: rgb(240, 230, 240);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 230, 191, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(240, 230, 240);\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 280, 191, 41))
        self.pushButton_3.setStyleSheet("background-color: rgb(240, 230, 240);\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 330, 191, 41))
        self.pushButton_4.setStyleSheet("background-color: rgb(240, 230, 240);\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 500, 191, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1341, 61))
        self.frame_2.setStyleSheet("background-color: rgb(26, 26, 62)\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(130, 0, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 100, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(230, 60, 1071, 761))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("background-color: rgb(240, 230, 240)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setGeometry(QtCore.QRect(40, 20, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(40, 80, 1001, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(26, 26, 62);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(20, 20, 111, 91))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.patient_name = QtWidgets.QLabel(parent=self.frame_4)
        self.patient_name.setGeometry(QtCore.QRect(170, 30, 411, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patient_name.sizePolicy().hasHeightForWidth())
        self.patient_name.setSizePolicy(sizePolicy)
        self.patient_name.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 20px")
        self.patient_name.setObjectName("patient_name")
        self.next_btn = QtWidgets.QPushButton(parent=self.frame_4)
        self.next_btn.setGeometry(QtCore.QRect(850, 50, 111, 51))
        self.next_btn.setStyleSheet("background-color: rgb(240, 230, 240);\n"
"border-radius: 15px;")
        self.next_btn.setObjectName("next_btn")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame_4)
        self.layoutWidget.setGeometry(QtCore.QRect(170, 60, 511, 52))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.patient_id_label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.patient_id_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.patient_id_label.setObjectName("patient_id_label")
        self.gridLayout.addWidget(self.patient_id_label, 0, 0, 1, 1)
        self.placeholder_p_ID = QtWidgets.QLabel(parent=self.layoutWidget)
        self.placeholder_p_ID.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.placeholder_p_ID.setObjectName("placeholder_p_ID")
        self.gridLayout.addWidget(self.placeholder_p_ID, 0, 1, 1, 2)
        self.patient_id_label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.patient_id_label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.patient_id_label_3.setObjectName("patient_id_label_3")
        self.gridLayout.addWidget(self.patient_id_label_3, 0, 3, 1, 1)
        self.placeholder_register_date = QtWidgets.QLabel(parent=self.layoutWidget)
        self.placeholder_register_date.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.placeholder_register_date.setObjectName("placeholder_register_date")
        self.gridLayout.addWidget(self.placeholder_register_date, 0, 4, 1, 1)
        self.patient_id_label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.patient_id_label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.patient_id_label_4.setObjectName("patient_id_label_4")
        self.gridLayout.addWidget(self.patient_id_label_4, 1, 3, 1, 1)
        self.placeholder_philhealth_num = QtWidgets.QLabel(parent=self.layoutWidget)
        self.placeholder_philhealth_num.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.placeholder_philhealth_num.setObjectName("placeholder_philhealth_num")
        self.gridLayout.addWidget(self.placeholder_philhealth_num, 1, 4, 1, 1)
        self.patient_id_label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.patient_id_label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.patient_id_label_2.setObjectName("patient_id_label_2")
        self.gridLayout.addWidget(self.patient_id_label_2, 1, 0, 1, 1)
        self.placeholder_p_bloodType = QtWidgets.QLabel(parent=self.layoutWidget)
        self.placeholder_p_bloodType.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 16px")
        self.placeholder_p_bloodType.setObjectName("placeholder_p_bloodType")
        self.gridLayout.addWidget(self.placeholder_p_bloodType, 1, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.frame_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 240, 803, 40))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54; /* underline */\n"
"}\n"
"\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54; /* underline */\n"
"}\n"
"\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54; /* underline */\n"
"}\n"
"\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54; /* underline */\n"
"}\n"
"\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54; /* underline */\n"
"}\n"
"\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    color: rgb(26, 26, 62);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: #1a1a1a;\n"
"    border-bottom: 3px solid #2c2c54; /* underline */\n"
"}\n"
"\n"
"QPushButton:!checked {\n"
"    border-bottom: 3px solid transparent;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout.addWidget(self.pushButton_11)
        self.left = QtWidgets.QFrame(parent=self.frame_3)
        self.left.setGeometry(QtCore.QRect(60, 340, 471, 381))
        self.left.setStyleSheet("background-color:rgb(236, 198, 220);\n"
"    border: 1px solid rgb(158, 136, 163);\n"
"    border-radius: 15px;")
        self.left.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.left.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.left.setObjectName("left")
        self.left_prescription_date_and_purpose = QtWidgets.QTableWidget(parent=self.left)
        self.left_prescription_date_and_purpose.setGeometry(QtCore.QRect(0, 0, 471, 381))
        self.left_prescription_date_and_purpose.setAutoFillBackground(True)
        self.left_prescription_date_and_purpose.setStyleSheet("QTableWidget {\n"
"    background-color:rgb(236, 198, 220);\n"
"    border: 1px solid rgb(158, 136, 163);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    background-color: rgb(236, 198, 220);\n"
"    color: rgb(21, 23, 61);\n"
"    padding: 8px;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(210, 177, 200);\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: black;\n"
"    color: rgb(21, 23, 61);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(236, 198, 220);\n"
"    color: rgb(21, 23, 61);\n"
"    font-weight: bold;\n"
"    font-size: 10px;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(155, 132, 160);\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: white;\n"
"    width: 6px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(178, 100, 168);\n"
"    border-radius: 3px;\n"
"}")
        self.left_prescription_date_and_purpose.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.left_prescription_date_and_purpose.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.left_prescription_date_and_purpose.setAlternatingRowColors(False)
        self.left_prescription_date_and_purpose.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.left_prescription_date_and_purpose.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.left_prescription_date_and_purpose.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.left_prescription_date_and_purpose.setShowGrid(False)
        self.left_prescription_date_and_purpose.setColumnCount(3)
        self.left_prescription_date_and_purpose.setObjectName("left_prescription_date_and_purpose")
        self.left_prescription_date_and_purpose.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.left_prescription_date_and_purpose.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.left_prescription_date_and_purpose.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.left_prescription_date_and_purpose.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.left_prescription_date_and_purpose.setHorizontalHeaderItem(2, item)
        self.left_prescription_date_and_purpose.horizontalHeader().setCascadingSectionResizes(False)
        self.left_prescription_date_and_purpose.horizontalHeader().setDefaultSectionSize(150)
        self.left_prescription_date_and_purpose.horizontalHeader().setHighlightSections(True)
        self.left_prescription_date_and_purpose.horizontalHeader().setMinimumSectionSize(32)
        self.left_prescription_date_and_purpose.horizontalHeader().setSortIndicatorShown(False)
        self.left_prescription_date_and_purpose.horizontalHeader().setStretchLastSection(True)
        self.left_prescription_date_and_purpose.verticalHeader().setVisible(False)
        self.left_prescription_date_and_purpose.verticalHeader().setCascadingSectionResizes(False)
        self.left_prescription_date_and_purpose.verticalHeader().setDefaultSectionSize(40)
        self.right_details_prescription = QtWidgets.QFrame(parent=self.frame_3)
        self.right_details_prescription.setGeometry(QtCore.QRect(540, 340, 501, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_details_prescription.sizePolicy().hasHeightForWidth())
        self.right_details_prescription.setSizePolicy(sizePolicy)
        self.right_details_prescription.setStyleSheet("background-color:rgb(236, 198, 220);\n"
"    border: 1px solid rgb(158, 136, 163);\n"
"    border-radius: 15px;")
        self.right_details_prescription.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.right_details_prescription.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.right_details_prescription.setObjectName("right_details_prescription")
        self.patient_table_3 = QtWidgets.QTableWidget(parent=self.right_details_prescription)
        self.patient_table_3.setGeometry(QtCore.QRect(10, 58, 481, 251))
        self.patient_table_3.setAutoFillBackground(True)
        self.patient_table_3.setStyleSheet("QTableWidget {\n"
"    background-color:rgb(236, 198, 220);\n"
"    border: 1px solid rgb(158, 136, 163);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    background-color: rgb(236, 198, 220);\n"
"    color: rgb(21, 23, 61);\n"
"    padding: 8px;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(210, 177, 200);\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: black;\n"
"    color: rgb(21, 23, 61);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(236, 198, 220);\n"
"    color: rgb(21, 23, 61);\n"
"    font-weight: bold;\n"
"    font-size: 10px;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(155, 132, 160);\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: white;\n"
"    width: 6px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(178, 100, 168);\n"
"    border-radius: 3px;\n"
"}")
        self.patient_table_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.patient_table_3.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.patient_table_3.setAlternatingRowColors(False)
        self.patient_table_3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.patient_table_3.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.patient_table_3.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.patient_table_3.setShowGrid(False)
        self.patient_table_3.setColumnCount(6)
        self.patient_table_3.setObjectName("patient_table_3")
        self.patient_table_3.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table_3.setHorizontalHeaderItem(5, item)
        self.patient_table_3.horizontalHeader().setCascadingSectionResizes(False)
        self.patient_table_3.horizontalHeader().setDefaultSectionSize(110)
        self.patient_table_3.horizontalHeader().setHighlightSections(True)
        self.patient_table_3.horizontalHeader().setMinimumSectionSize(25)
        self.patient_table_3.horizontalHeader().setSortIndicatorShown(False)
        self.patient_table_3.horizontalHeader().setStretchLastSection(True)
        self.patient_table_3.verticalHeader().setVisible(False)
        self.patient_table_3.verticalHeader().setCascadingSectionResizes(False)
        self.patient_table_3.verticalHeader().setDefaultSectionSize(40)
        self.notes_label = QtWidgets.QLabel(parent=self.right_details_prescription)
        self.notes_label.setGeometry(QtCore.QRect(10, 330, 37, 18))
        self.notes_label.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"border: none;")
        self.notes_label.setObjectName("notes_label")
        self.notes_placeholder = QtWidgets.QLabel(parent=self.right_details_prescription)
        self.notes_placeholder.setGeometry(QtCore.QRect(60, 330, 67, 18))
        self.notes_placeholder.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"border: none;")
        self.notes_placeholder.setObjectName("notes_placeholder")
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.right_details_prescription)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 229, 44))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.date_label = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.date_label.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"border: none;")
        self.date_label.setObjectName("date_label")
        self.gridLayout_2.addWidget(self.date_label, 1, 0, 1, 1)
        self.date_prescription_date_placeholder = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.date_prescription_date_placeholder.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"border: none;")
        self.date_prescription_date_placeholder.setObjectName("date_prescription_date_placeholder")
        self.gridLayout_2.addWidget(self.date_prescription_date_placeholder, 1, 1, 1, 1)
        self.prescribed_by = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.prescribed_by.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"border: none;")
        self.prescribed_by.setObjectName("prescribed_by")
        self.gridLayout_2.addWidget(self.prescribed_by, 0, 0, 1, 1)
        self.prescribed_by_placeholder = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.prescribed_by_placeholder.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"border: none;")
        self.prescribed_by_placeholder.setObjectName("prescribed_by_placeholder")
        self.gridLayout_2.addWidget(self.prescribed_by_placeholder, 0, 1, 1, 1)
        self.ad_prescription = QtWidgets.QPushButton(parent=self.frame_3)
        self.ad_prescription.setGeometry(QtCore.QRect(920, 300, 121, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ad_prescription.sizePolicy().hasHeightForWidth())
        self.ad_prescription.setSizePolicy(sizePolicy)
        self.ad_prescription.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(236, 198, 220);\n"
"border: 1px solid rgb(210, 177, 200);")
        self.ad_prescription.setObjectName("ad_prescription")
        self.edit_prescription = QtWidgets.QPushButton(parent=self.frame_3)
        self.edit_prescription.setGeometry(QtCore.QRect(790, 300, 121, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_prescription.sizePolicy().hasHeightForWidth())
        self.edit_prescription.setSizePolicy(sizePolicy)
        self.edit_prescription.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(236, 198, 220);\n"
"border: 1px solid rgb(210, 177, 200);")
        self.edit_prescription.setObjectName("edit_prescription")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1301, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_2.setText(_translate("MainWindow", "Patient Records"))
        self.pushButton_3.setText(_translate("MainWindow", "Prenatal Care"))
        self.pushButton_4.setText(_translate("MainWindow", "        Appointments        "))
        self.pushButton_5.setText(_translate("MainWindow", "Log out"))
        self.label_2.setText(_translate("MainWindow", "MATERNADB"))
        self.label_3.setText(_translate("MainWindow", "LOGO"))
        self.label.setText(_translate("MainWindow", "Patient Records"))
        self.patient_name.setText(_translate("MainWindow", "NAME"))
        self.next_btn.setText(_translate("MainWindow", "Next"))
        self.patient_id_label.setText(_translate("MainWindow", "Patient ID:"))
        self.placeholder_p_ID.setText(_translate("MainWindow", "placeholder"))
        self.patient_id_label_3.setText(_translate("MainWindow", "Registered:"))
        self.placeholder_register_date.setText(_translate("MainWindow", "MM/DD/YYYY"))
        self.patient_id_label_4.setText(_translate("MainWindow", "PhilHealth#:"))
        self.placeholder_philhealth_num.setText(_translate("MainWindow", "1234-5676-8907"))
        self.patient_id_label_2.setText(_translate("MainWindow", "Blood Type:"))
        self.placeholder_p_bloodType.setText(_translate("MainWindow", "placeholder"))
        self.pushButton_6.setText(_translate("MainWindow", "Patient Profile"))
        self.pushButton_7.setText(_translate("MainWindow", "Past Pregnancy"))
        self.pushButton_8.setText(_translate("MainWindow", "Prescriptions"))
        self.pushButton_9.setText(_translate("MainWindow", "Medical History"))
        self.pushButton_10.setText(_translate("MainWindow", "Family Planning"))
        self.pushButton_11.setText(_translate("MainWindow", "Appointments"))
        item = self.left_prescription_date_and_purpose.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "#0001"))
        item = self.left_prescription_date_and_purpose.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PRESCRIPTION DATE"))
        item = self.left_prescription_date_and_purpose.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "STAFF"))
        item = self.left_prescription_date_and_purpose.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ACTION"))
        item = self.patient_table_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "#0001"))
        item = self.patient_table_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "MEDICATION"))
        item = self.patient_table_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DOSE"))
        item = self.patient_table_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "FREQUENCY"))
        item = self.patient_table_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "DURATION"))
        item = self.patient_table_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ROUTE"))
        item = self.patient_table_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "TIMING"))
        self.notes_label.setText(_translate("MainWindow", "Notes:"))
        self.notes_placeholder.setText(_translate("MainWindow", "Placeholder"))
        self.date_label.setText(_translate("MainWindow", "Date:"))
        self.date_prescription_date_placeholder.setText(_translate("MainWindow", "Placeholder"))
        self.prescribed_by.setText(_translate("MainWindow", "Prescribed by:"))
        self.prescribed_by_placeholder.setText(_translate("MainWindow", "Placeholder"))
        self.ad_prescription.setText(_translate("MainWindow", "Add Prescription"))
        self.edit_prescription.setText(_translate("MainWindow", "Edit Prescription"))
